// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetFunction
    {
        public static Task<GetFunctionResult> InvokeAsync(GetFunctionArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetFunctionResult>("yandex:index/getFunction:getFunction", args ?? new GetFunctionArgs(), options.WithVersion());
    }


    public sealed class GetFunctionArgs : Pulumi.InvokeArgs
    {
        [Input("folderId")]
        public string? FolderId { get; set; }

        [Input("functionId")]
        public string? FunctionId { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        public GetFunctionArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetFunctionResult
    {
        public readonly string CreatedAt;
        public readonly string Description;
        public readonly string Entrypoint;
        public readonly ImmutableDictionary<string, string> Environment;
        public readonly string ExecutionTimeout;
        public readonly string? FolderId;
        public readonly string? FunctionId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly int ImageSize;
        public readonly ImmutableDictionary<string, string> Labels;
        public readonly string LoggroupId;
        public readonly int Memory;
        public readonly string? Name;
        public readonly string Runtime;
        public readonly string ServiceAccountId;
        public readonly ImmutableArray<string> Tags;
        public readonly string Version;

        [OutputConstructor]
        private GetFunctionResult(
            string createdAt,

            string description,

            string entrypoint,

            ImmutableDictionary<string, string> environment,

            string executionTimeout,

            string? folderId,

            string? functionId,

            string id,

            int imageSize,

            ImmutableDictionary<string, string> labels,

            string loggroupId,

            int memory,

            string? name,

            string runtime,

            string serviceAccountId,

            ImmutableArray<string> tags,

            string version)
        {
            CreatedAt = createdAt;
            Description = description;
            Entrypoint = entrypoint;
            Environment = environment;
            ExecutionTimeout = executionTimeout;
            FolderId = folderId;
            FunctionId = functionId;
            Id = id;
            ImageSize = imageSize;
            Labels = labels;
            LoggroupId = loggroupId;
            Memory = memory;
            Name = name;
            Runtime = runtime;
            ServiceAccountId = serviceAccountId;
            Tags = tags;
            Version = version;
        }
    }
}
