// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetFunctionTrigger
    {
        public static Task<GetFunctionTriggerResult> InvokeAsync(GetFunctionTriggerArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetFunctionTriggerResult>("yandex:index/getFunctionTrigger:getFunctionTrigger", args ?? new GetFunctionTriggerArgs(), options.WithVersion());
    }


    public sealed class GetFunctionTriggerArgs : Pulumi.InvokeArgs
    {
        [Input("folderId")]
        public string? FolderId { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        [Input("triggerId")]
        public string? TriggerId { get; set; }

        public GetFunctionTriggerArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetFunctionTriggerResult
    {
        public readonly string CreatedAt;
        public readonly string Description;
        public readonly Outputs.GetFunctionTriggerDlqResult Dlq;
        public readonly string? FolderId;
        public readonly Outputs.GetFunctionTriggerFunctionResult Function;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly Outputs.GetFunctionTriggerIotResult Iot;
        public readonly ImmutableDictionary<string, string> Labels;
        public readonly Outputs.GetFunctionTriggerMessageQueueResult MessageQueue;
        public readonly string? Name;
        public readonly Outputs.GetFunctionTriggerObjectStorageResult ObjectStorage;
        public readonly Outputs.GetFunctionTriggerTimerResult Timer;
        public readonly string? TriggerId;

        [OutputConstructor]
        private GetFunctionTriggerResult(
            string createdAt,

            string description,

            Outputs.GetFunctionTriggerDlqResult dlq,

            string? folderId,

            Outputs.GetFunctionTriggerFunctionResult function,

            string id,

            Outputs.GetFunctionTriggerIotResult iot,

            ImmutableDictionary<string, string> labels,

            Outputs.GetFunctionTriggerMessageQueueResult messageQueue,

            string? name,

            Outputs.GetFunctionTriggerObjectStorageResult objectStorage,

            Outputs.GetFunctionTriggerTimerResult timer,

            string? triggerId)
        {
            CreatedAt = createdAt;
            Description = description;
            Dlq = dlq;
            FolderId = folderId;
            Function = function;
            Id = id;
            Iot = iot;
            Labels = labels;
            MessageQueue = messageQueue;
            Name = name;
            ObjectStorage = objectStorage;
            Timer = timer;
            TriggerId = triggerId;
        }
    }
}
