// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetIamPolicy
    {
        public static Task<GetIamPolicyResult> InvokeAsync(GetIamPolicyArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetIamPolicyResult>("yandex:index/getIamPolicy:getIamPolicy", args ?? new GetIamPolicyArgs(), options.WithVersion());
    }


    public sealed class GetIamPolicyArgs : Pulumi.InvokeArgs
    {
        [Input("bindings", required: true)]
        private List<Inputs.GetIamPolicyBindingArgs>? _bindings;
        public List<Inputs.GetIamPolicyBindingArgs> Bindings
        {
            get => _bindings ?? (_bindings = new List<Inputs.GetIamPolicyBindingArgs>());
            set => _bindings = value;
        }

        public GetIamPolicyArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetIamPolicyResult
    {
        public readonly ImmutableArray<Outputs.GetIamPolicyBindingResult> Bindings;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string PolicyData;

        [OutputConstructor]
        private GetIamPolicyResult(
            ImmutableArray<Outputs.GetIamPolicyBindingResult> bindings,

            string id,

            string policyData)
        {
            Bindings = bindings;
            Id = id;
            PolicyData = policyData;
        }
    }
}
