// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetIamServiceAccount
    {
        public static Task<GetIamServiceAccountResult> InvokeAsync(GetIamServiceAccountArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetIamServiceAccountResult>("yandex:index/getIamServiceAccount:getIamServiceAccount", args ?? new GetIamServiceAccountArgs(), options.WithVersion());
    }


    public sealed class GetIamServiceAccountArgs : Pulumi.InvokeArgs
    {
        [Input("folderId")]
        public string? FolderId { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        [Input("serviceAccountId")]
        public string? ServiceAccountId { get; set; }

        public GetIamServiceAccountArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetIamServiceAccountResult
    {
        public readonly string CreatedAt;
        public readonly string Description;
        public readonly string FolderId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string ServiceAccountId;

        [OutputConstructor]
        private GetIamServiceAccountResult(
            string createdAt,

            string description,

            string folderId,

            string id,

            string name,

            string serviceAccountId)
        {
            CreatedAt = createdAt;
            Description = description;
            FolderId = folderId;
            Id = id;
            Name = name;
            ServiceAccountId = serviceAccountId;
        }
    }
}
