// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetLbTargetGroup
    {
        public static Task<GetLbTargetGroupResult> InvokeAsync(GetLbTargetGroupArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetLbTargetGroupResult>("yandex:index/getLbTargetGroup:getLbTargetGroup", args ?? new GetLbTargetGroupArgs(), options.WithVersion());
    }


    public sealed class GetLbTargetGroupArgs : Pulumi.InvokeArgs
    {
        [Input("folderId")]
        public string? FolderId { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        [Input("targetGroupId")]
        public string? TargetGroupId { get; set; }

        public GetLbTargetGroupArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetLbTargetGroupResult
    {
        public readonly string CreatedAt;
        public readonly string Description;
        public readonly string FolderId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableDictionary<string, string> Labels;
        public readonly string Name;
        public readonly string TargetGroupId;
        public readonly ImmutableArray<Outputs.GetLbTargetGroupTargetResult> Targets;

        [OutputConstructor]
        private GetLbTargetGroupResult(
            string createdAt,

            string description,

            string folderId,

            string id,

            ImmutableDictionary<string, string> labels,

            string name,

            string targetGroupId,

            ImmutableArray<Outputs.GetLbTargetGroupTargetResult> targets)
        {
            CreatedAt = createdAt;
            Description = description;
            FolderId = folderId;
            Id = id;
            Labels = labels;
            Name = name;
            TargetGroupId = targetGroupId;
            Targets = targets;
        }
    }
}
