// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    [YandexResourceType("yandex:index/kubernetesNodeGroup:KubernetesNodeGroup")]
    public partial class KubernetesNodeGroup : Pulumi.CustomResource
    {
        [Output("allocationPolicy")]
        public Output<Outputs.KubernetesNodeGroupAllocationPolicy> AllocationPolicy { get; private set; } = null!;

        [Output("allowedUnsafeSysctls")]
        public Output<ImmutableArray<string>> AllowedUnsafeSysctls { get; private set; } = null!;

        [Output("clusterId")]
        public Output<string> ClusterId { get; private set; } = null!;

        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        [Output("deployPolicy")]
        public Output<Outputs.KubernetesNodeGroupDeployPolicy> DeployPolicy { get; private set; } = null!;

        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        [Output("instanceGroupId")]
        public Output<string> InstanceGroupId { get; private set; } = null!;

        [Output("instanceTemplate")]
        public Output<Outputs.KubernetesNodeGroupInstanceTemplate> InstanceTemplate { get; private set; } = null!;

        [Output("labels")]
        public Output<ImmutableDictionary<string, string>> Labels { get; private set; } = null!;

        [Output("maintenancePolicy")]
        public Output<Outputs.KubernetesNodeGroupMaintenancePolicy> MaintenancePolicy { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("nodeLabels")]
        public Output<ImmutableDictionary<string, string>?> NodeLabels { get; private set; } = null!;

        [Output("nodeTaints")]
        public Output<ImmutableArray<string>> NodeTaints { get; private set; } = null!;

        [Output("scalePolicy")]
        public Output<Outputs.KubernetesNodeGroupScalePolicy> ScalePolicy { get; private set; } = null!;

        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        [Output("version")]
        public Output<string> Version { get; private set; } = null!;

        [Output("versionInfo")]
        public Output<Outputs.KubernetesNodeGroupVersionInfo> VersionInfo { get; private set; } = null!;


        /// <summary>
        /// Create a KubernetesNodeGroup resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public KubernetesNodeGroup(string name, KubernetesNodeGroupArgs args, CustomResourceOptions? options = null)
            : base("yandex:index/kubernetesNodeGroup:KubernetesNodeGroup", name, args ?? new KubernetesNodeGroupArgs(), MakeResourceOptions(options, ""))
        {
        }

        private KubernetesNodeGroup(string name, Input<string> id, KubernetesNodeGroupState? state = null, CustomResourceOptions? options = null)
            : base("yandex:index/kubernetesNodeGroup:KubernetesNodeGroup", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing KubernetesNodeGroup resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static KubernetesNodeGroup Get(string name, Input<string> id, KubernetesNodeGroupState? state = null, CustomResourceOptions? options = null)
        {
            return new KubernetesNodeGroup(name, id, state, options);
        }
    }

    public sealed class KubernetesNodeGroupArgs : Pulumi.ResourceArgs
    {
        [Input("allocationPolicy")]
        public Input<Inputs.KubernetesNodeGroupAllocationPolicyArgs>? AllocationPolicy { get; set; }

        [Input("allowedUnsafeSysctls")]
        private InputList<string>? _allowedUnsafeSysctls;
        public InputList<string> AllowedUnsafeSysctls
        {
            get => _allowedUnsafeSysctls ?? (_allowedUnsafeSysctls = new InputList<string>());
            set => _allowedUnsafeSysctls = value;
        }

        [Input("clusterId", required: true)]
        public Input<string> ClusterId { get; set; } = null!;

        [Input("deployPolicy")]
        public Input<Inputs.KubernetesNodeGroupDeployPolicyArgs>? DeployPolicy { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("instanceTemplate", required: true)]
        public Input<Inputs.KubernetesNodeGroupInstanceTemplateArgs> InstanceTemplate { get; set; } = null!;

        [Input("labels")]
        private InputMap<string>? _labels;
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("maintenancePolicy")]
        public Input<Inputs.KubernetesNodeGroupMaintenancePolicyArgs>? MaintenancePolicy { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("nodeLabels")]
        private InputMap<string>? _nodeLabels;
        public InputMap<string> NodeLabels
        {
            get => _nodeLabels ?? (_nodeLabels = new InputMap<string>());
            set => _nodeLabels = value;
        }

        [Input("nodeTaints")]
        private InputList<string>? _nodeTaints;
        public InputList<string> NodeTaints
        {
            get => _nodeTaints ?? (_nodeTaints = new InputList<string>());
            set => _nodeTaints = value;
        }

        [Input("scalePolicy", required: true)]
        public Input<Inputs.KubernetesNodeGroupScalePolicyArgs> ScalePolicy { get; set; } = null!;

        [Input("version")]
        public Input<string>? Version { get; set; }

        public KubernetesNodeGroupArgs()
        {
        }
    }

    public sealed class KubernetesNodeGroupState : Pulumi.ResourceArgs
    {
        [Input("allocationPolicy")]
        public Input<Inputs.KubernetesNodeGroupAllocationPolicyGetArgs>? AllocationPolicy { get; set; }

        [Input("allowedUnsafeSysctls")]
        private InputList<string>? _allowedUnsafeSysctls;
        public InputList<string> AllowedUnsafeSysctls
        {
            get => _allowedUnsafeSysctls ?? (_allowedUnsafeSysctls = new InputList<string>());
            set => _allowedUnsafeSysctls = value;
        }

        [Input("clusterId")]
        public Input<string>? ClusterId { get; set; }

        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("deployPolicy")]
        public Input<Inputs.KubernetesNodeGroupDeployPolicyGetArgs>? DeployPolicy { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("instanceGroupId")]
        public Input<string>? InstanceGroupId { get; set; }

        [Input("instanceTemplate")]
        public Input<Inputs.KubernetesNodeGroupInstanceTemplateGetArgs>? InstanceTemplate { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("maintenancePolicy")]
        public Input<Inputs.KubernetesNodeGroupMaintenancePolicyGetArgs>? MaintenancePolicy { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("nodeLabels")]
        private InputMap<string>? _nodeLabels;
        public InputMap<string> NodeLabels
        {
            get => _nodeLabels ?? (_nodeLabels = new InputMap<string>());
            set => _nodeLabels = value;
        }

        [Input("nodeTaints")]
        private InputList<string>? _nodeTaints;
        public InputList<string> NodeTaints
        {
            get => _nodeTaints ?? (_nodeTaints = new InputList<string>());
            set => _nodeTaints = value;
        }

        [Input("scalePolicy")]
        public Input<Inputs.KubernetesNodeGroupScalePolicyGetArgs>? ScalePolicy { get; set; }

        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("version")]
        public Input<string>? Version { get; set; }

        [Input("versionInfo")]
        public Input<Inputs.KubernetesNodeGroupVersionInfoGetArgs>? VersionInfo { get; set; }

        public KubernetesNodeGroupState()
        {
        }
    }
}
