// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    [YandexResourceType("yandex:index/lbNetworkLoad_balancer:LbNetworkLoad_balancer")]
    public partial class LbNetworkLoad_balancer : Pulumi.CustomResource
    {
        [Output("attachedTargetGroups")]
        public Output<ImmutableArray<Outputs.LbNetworkLoad_balancerAttachedTargetGroup>> AttachedTargetGroups { get; private set; } = null!;

        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        [Output("folderId")]
        public Output<string> FolderId { get; private set; } = null!;

        [Output("labels")]
        public Output<ImmutableDictionary<string, string>?> Labels { get; private set; } = null!;

        [Output("listeners")]
        public Output<ImmutableArray<Outputs.LbNetworkLoad_balancerListener>> Listeners { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("regionId")]
        public Output<string?> RegionId { get; private set; } = null!;

        [Output("type")]
        public Output<string?> Type { get; private set; } = null!;


        /// <summary>
        /// Create a LbNetworkLoad_balancer resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public LbNetworkLoad_balancer(string name, LbNetworkLoad_balancerArgs? args = null, CustomResourceOptions? options = null)
            : base("yandex:index/lbNetworkLoad_balancer:LbNetworkLoad_balancer", name, args ?? new LbNetworkLoad_balancerArgs(), MakeResourceOptions(options, ""))
        {
        }

        private LbNetworkLoad_balancer(string name, Input<string> id, LbNetworkLoad_balancerState? state = null, CustomResourceOptions? options = null)
            : base("yandex:index/lbNetworkLoad_balancer:LbNetworkLoad_balancer", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing LbNetworkLoad_balancer resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static LbNetworkLoad_balancer Get(string name, Input<string> id, LbNetworkLoad_balancerState? state = null, CustomResourceOptions? options = null)
        {
            return new LbNetworkLoad_balancer(name, id, state, options);
        }
    }

    public sealed class LbNetworkLoad_balancerArgs : Pulumi.ResourceArgs
    {
        [Input("attachedTargetGroups")]
        private InputList<Inputs.LbNetworkLoad_balancerAttachedTargetGroupArgs>? _attachedTargetGroups;
        public InputList<Inputs.LbNetworkLoad_balancerAttachedTargetGroupArgs> AttachedTargetGroups
        {
            get => _attachedTargetGroups ?? (_attachedTargetGroups = new InputList<Inputs.LbNetworkLoad_balancerAttachedTargetGroupArgs>());
            set => _attachedTargetGroups = value;
        }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("listeners")]
        private InputList<Inputs.LbNetworkLoad_balancerListenerArgs>? _listeners;
        public InputList<Inputs.LbNetworkLoad_balancerListenerArgs> Listeners
        {
            get => _listeners ?? (_listeners = new InputList<Inputs.LbNetworkLoad_balancerListenerArgs>());
            set => _listeners = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("regionId")]
        public Input<string>? RegionId { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public LbNetworkLoad_balancerArgs()
        {
        }
    }

    public sealed class LbNetworkLoad_balancerState : Pulumi.ResourceArgs
    {
        [Input("attachedTargetGroups")]
        private InputList<Inputs.LbNetworkLoad_balancerAttachedTargetGroupGetArgs>? _attachedTargetGroups;
        public InputList<Inputs.LbNetworkLoad_balancerAttachedTargetGroupGetArgs> AttachedTargetGroups
        {
            get => _attachedTargetGroups ?? (_attachedTargetGroups = new InputList<Inputs.LbNetworkLoad_balancerAttachedTargetGroupGetArgs>());
            set => _attachedTargetGroups = value;
        }

        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("listeners")]
        private InputList<Inputs.LbNetworkLoad_balancerListenerGetArgs>? _listeners;
        public InputList<Inputs.LbNetworkLoad_balancerListenerGetArgs> Listeners
        {
            get => _listeners ?? (_listeners = new InputList<Inputs.LbNetworkLoad_balancerListenerGetArgs>());
            set => _listeners = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("regionId")]
        public Input<string>? RegionId { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public LbNetworkLoad_balancerState()
        {
        }
    }
}
