// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    [YandexResourceType("yandex:index/mdbKafkaCluster:MdbKafkaCluster")]
    public partial class MdbKafkaCluster : Pulumi.CustomResource
    {
        [Output("config")]
        public Output<Outputs.MdbKafkaClusterConfig> Config { get; private set; } = null!;

        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        [Output("environment")]
        public Output<string?> Environment { get; private set; } = null!;

        [Output("folderId")]
        public Output<string> FolderId { get; private set; } = null!;

        [Output("health")]
        public Output<string> Health { get; private set; } = null!;

        [Output("labels")]
        public Output<ImmutableDictionary<string, string>?> Labels { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("networkId")]
        public Output<string> NetworkId { get; private set; } = null!;

        [Output("securityGroupIds")]
        public Output<ImmutableArray<string>> SecurityGroupIds { get; private set; } = null!;

        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        [Output("subnetIds")]
        public Output<ImmutableArray<string>> SubnetIds { get; private set; } = null!;

        [Output("topics")]
        public Output<ImmutableArray<Outputs.MdbKafkaClusterTopic>> Topics { get; private set; } = null!;

        [Output("users")]
        public Output<ImmutableArray<Outputs.MdbKafkaClusterUser>> Users { get; private set; } = null!;


        /// <summary>
        /// Create a MdbKafkaCluster resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MdbKafkaCluster(string name, MdbKafkaClusterArgs args, CustomResourceOptions? options = null)
            : base("yandex:index/mdbKafkaCluster:MdbKafkaCluster", name, args ?? new MdbKafkaClusterArgs(), MakeResourceOptions(options, ""))
        {
        }

        private MdbKafkaCluster(string name, Input<string> id, MdbKafkaClusterState? state = null, CustomResourceOptions? options = null)
            : base("yandex:index/mdbKafkaCluster:MdbKafkaCluster", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing MdbKafkaCluster resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static MdbKafkaCluster Get(string name, Input<string> id, MdbKafkaClusterState? state = null, CustomResourceOptions? options = null)
        {
            return new MdbKafkaCluster(name, id, state, options);
        }
    }

    public sealed class MdbKafkaClusterArgs : Pulumi.ResourceArgs
    {
        [Input("config", required: true)]
        public Input<Inputs.MdbKafkaClusterConfigArgs> Config { get; set; } = null!;

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("environment")]
        public Input<string>? Environment { get; set; }

        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("networkId", required: true)]
        public Input<string> NetworkId { get; set; } = null!;

        [Input("securityGroupIds")]
        private InputList<string>? _securityGroupIds;
        public InputList<string> SecurityGroupIds
        {
            get => _securityGroupIds ?? (_securityGroupIds = new InputList<string>());
            set => _securityGroupIds = value;
        }

        [Input("subnetIds")]
        private InputList<string>? _subnetIds;
        public InputList<string> SubnetIds
        {
            get => _subnetIds ?? (_subnetIds = new InputList<string>());
            set => _subnetIds = value;
        }

        [Input("topics")]
        private InputList<Inputs.MdbKafkaClusterTopicArgs>? _topics;
        public InputList<Inputs.MdbKafkaClusterTopicArgs> Topics
        {
            get => _topics ?? (_topics = new InputList<Inputs.MdbKafkaClusterTopicArgs>());
            set => _topics = value;
        }

        [Input("users")]
        private InputList<Inputs.MdbKafkaClusterUserArgs>? _users;
        public InputList<Inputs.MdbKafkaClusterUserArgs> Users
        {
            get => _users ?? (_users = new InputList<Inputs.MdbKafkaClusterUserArgs>());
            set => _users = value;
        }

        public MdbKafkaClusterArgs()
        {
        }
    }

    public sealed class MdbKafkaClusterState : Pulumi.ResourceArgs
    {
        [Input("config")]
        public Input<Inputs.MdbKafkaClusterConfigGetArgs>? Config { get; set; }

        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("environment")]
        public Input<string>? Environment { get; set; }

        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        [Input("health")]
        public Input<string>? Health { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("networkId")]
        public Input<string>? NetworkId { get; set; }

        [Input("securityGroupIds")]
        private InputList<string>? _securityGroupIds;
        public InputList<string> SecurityGroupIds
        {
            get => _securityGroupIds ?? (_securityGroupIds = new InputList<string>());
            set => _securityGroupIds = value;
        }

        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("subnetIds")]
        private InputList<string>? _subnetIds;
        public InputList<string> SubnetIds
        {
            get => _subnetIds ?? (_subnetIds = new InputList<string>());
            set => _subnetIds = value;
        }

        [Input("topics")]
        private InputList<Inputs.MdbKafkaClusterTopicGetArgs>? _topics;
        public InputList<Inputs.MdbKafkaClusterTopicGetArgs> Topics
        {
            get => _topics ?? (_topics = new InputList<Inputs.MdbKafkaClusterTopicGetArgs>());
            set => _topics = value;
        }

        [Input("users")]
        private InputList<Inputs.MdbKafkaClusterUserGetArgs>? _users;
        public InputList<Inputs.MdbKafkaClusterUserGetArgs> Users
        {
            get => _users ?? (_users = new InputList<Inputs.MdbKafkaClusterUserGetArgs>());
            set => _users = value;
        }

        public MdbKafkaClusterState()
        {
        }
    }
}
