// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    [YandexResourceType("yandex:index/mdbMysqlCluster:MdbMysqlCluster")]
    public partial class MdbMysqlCluster : Pulumi.CustomResource
    {
        [Output("access")]
        public Output<Outputs.MdbMysqlClusterAccess> Access { get; private set; } = null!;

        [Output("backupWindowStart")]
        public Output<Outputs.MdbMysqlClusterBackupWindowStart> BackupWindowStart { get; private set; } = null!;

        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        [Output("databases")]
        public Output<ImmutableArray<Outputs.MdbMysqlClusterDatabase>> Databases { get; private set; } = null!;

        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        [Output("environment")]
        public Output<string> Environment { get; private set; } = null!;

        [Output("folderId")]
        public Output<string> FolderId { get; private set; } = null!;

        [Output("health")]
        public Output<string> Health { get; private set; } = null!;

        [Output("hosts")]
        public Output<ImmutableArray<Outputs.MdbMysqlClusterHost>> Hosts { get; private set; } = null!;

        [Output("labels")]
        public Output<ImmutableDictionary<string, string>?> Labels { get; private set; } = null!;

        [Output("mysqlConfig")]
        public Output<ImmutableDictionary<string, string>> MysqlConfig { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("networkId")]
        public Output<string> NetworkId { get; private set; } = null!;

        [Output("resources")]
        public Output<Outputs.MdbMysqlClusterResources> Resources { get; private set; } = null!;

        [Output("restore")]
        public Output<Outputs.MdbMysqlClusterRestore?> Restore { get; private set; } = null!;

        [Output("securityGroupIds")]
        public Output<ImmutableArray<string>> SecurityGroupIds { get; private set; } = null!;

        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        [Output("users")]
        public Output<ImmutableArray<Outputs.MdbMysqlClusterUser>> Users { get; private set; } = null!;

        [Output("version")]
        public Output<string> Version { get; private set; } = null!;


        /// <summary>
        /// Create a MdbMysqlCluster resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MdbMysqlCluster(string name, MdbMysqlClusterArgs args, CustomResourceOptions? options = null)
            : base("yandex:index/mdbMysqlCluster:MdbMysqlCluster", name, args ?? new MdbMysqlClusterArgs(), MakeResourceOptions(options, ""))
        {
        }

        private MdbMysqlCluster(string name, Input<string> id, MdbMysqlClusterState? state = null, CustomResourceOptions? options = null)
            : base("yandex:index/mdbMysqlCluster:MdbMysqlCluster", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing MdbMysqlCluster resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static MdbMysqlCluster Get(string name, Input<string> id, MdbMysqlClusterState? state = null, CustomResourceOptions? options = null)
        {
            return new MdbMysqlCluster(name, id, state, options);
        }
    }

    public sealed class MdbMysqlClusterArgs : Pulumi.ResourceArgs
    {
        [Input("access")]
        public Input<Inputs.MdbMysqlClusterAccessArgs>? Access { get; set; }

        [Input("backupWindowStart")]
        public Input<Inputs.MdbMysqlClusterBackupWindowStartArgs>? BackupWindowStart { get; set; }

        [Input("databases", required: true)]
        private InputList<Inputs.MdbMysqlClusterDatabaseArgs>? _databases;
        public InputList<Inputs.MdbMysqlClusterDatabaseArgs> Databases
        {
            get => _databases ?? (_databases = new InputList<Inputs.MdbMysqlClusterDatabaseArgs>());
            set => _databases = value;
        }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("environment", required: true)]
        public Input<string> Environment { get; set; } = null!;

        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        [Input("hosts", required: true)]
        private InputList<Inputs.MdbMysqlClusterHostArgs>? _hosts;
        public InputList<Inputs.MdbMysqlClusterHostArgs> Hosts
        {
            get => _hosts ?? (_hosts = new InputList<Inputs.MdbMysqlClusterHostArgs>());
            set => _hosts = value;
        }

        [Input("labels")]
        private InputMap<string>? _labels;
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("mysqlConfig")]
        private InputMap<string>? _mysqlConfig;
        public InputMap<string> MysqlConfig
        {
            get => _mysqlConfig ?? (_mysqlConfig = new InputMap<string>());
            set => _mysqlConfig = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("networkId", required: true)]
        public Input<string> NetworkId { get; set; } = null!;

        [Input("resources", required: true)]
        public Input<Inputs.MdbMysqlClusterResourcesArgs> Resources { get; set; } = null!;

        [Input("restore")]
        public Input<Inputs.MdbMysqlClusterRestoreArgs>? Restore { get; set; }

        [Input("securityGroupIds")]
        private InputList<string>? _securityGroupIds;
        public InputList<string> SecurityGroupIds
        {
            get => _securityGroupIds ?? (_securityGroupIds = new InputList<string>());
            set => _securityGroupIds = value;
        }

        [Input("users", required: true)]
        private InputList<Inputs.MdbMysqlClusterUserArgs>? _users;
        public InputList<Inputs.MdbMysqlClusterUserArgs> Users
        {
            get => _users ?? (_users = new InputList<Inputs.MdbMysqlClusterUserArgs>());
            set => _users = value;
        }

        [Input("version", required: true)]
        public Input<string> Version { get; set; } = null!;

        public MdbMysqlClusterArgs()
        {
        }
    }

    public sealed class MdbMysqlClusterState : Pulumi.ResourceArgs
    {
        [Input("access")]
        public Input<Inputs.MdbMysqlClusterAccessGetArgs>? Access { get; set; }

        [Input("backupWindowStart")]
        public Input<Inputs.MdbMysqlClusterBackupWindowStartGetArgs>? BackupWindowStart { get; set; }

        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("databases")]
        private InputList<Inputs.MdbMysqlClusterDatabaseGetArgs>? _databases;
        public InputList<Inputs.MdbMysqlClusterDatabaseGetArgs> Databases
        {
            get => _databases ?? (_databases = new InputList<Inputs.MdbMysqlClusterDatabaseGetArgs>());
            set => _databases = value;
        }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("environment")]
        public Input<string>? Environment { get; set; }

        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        [Input("health")]
        public Input<string>? Health { get; set; }

        [Input("hosts")]
        private InputList<Inputs.MdbMysqlClusterHostGetArgs>? _hosts;
        public InputList<Inputs.MdbMysqlClusterHostGetArgs> Hosts
        {
            get => _hosts ?? (_hosts = new InputList<Inputs.MdbMysqlClusterHostGetArgs>());
            set => _hosts = value;
        }

        [Input("labels")]
        private InputMap<string>? _labels;
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("mysqlConfig")]
        private InputMap<string>? _mysqlConfig;
        public InputMap<string> MysqlConfig
        {
            get => _mysqlConfig ?? (_mysqlConfig = new InputMap<string>());
            set => _mysqlConfig = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("networkId")]
        public Input<string>? NetworkId { get; set; }

        [Input("resources")]
        public Input<Inputs.MdbMysqlClusterResourcesGetArgs>? Resources { get; set; }

        [Input("restore")]
        public Input<Inputs.MdbMysqlClusterRestoreGetArgs>? Restore { get; set; }

        [Input("securityGroupIds")]
        private InputList<string>? _securityGroupIds;
        public InputList<string> SecurityGroupIds
        {
            get => _securityGroupIds ?? (_securityGroupIds = new InputList<string>());
            set => _securityGroupIds = value;
        }

        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("users")]
        private InputList<Inputs.MdbMysqlClusterUserGetArgs>? _users;
        public InputList<Inputs.MdbMysqlClusterUserGetArgs> Users
        {
            get => _users ?? (_users = new InputList<Inputs.MdbMysqlClusterUserGetArgs>());
            set => _users = value;
        }

        [Input("version")]
        public Input<string>? Version { get; set; }

        public MdbMysqlClusterState()
        {
        }
    }
}
