// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    [YandexResourceType("yandex:index/resourcemanagerFolderIamPolicy:ResourcemanagerFolderIamPolicy")]
    public partial class ResourcemanagerFolderIamPolicy : Pulumi.CustomResource
    {
        [Output("folderId")]
        public Output<string> FolderId { get; private set; } = null!;

        [Output("policyData")]
        public Output<string> PolicyData { get; private set; } = null!;


        /// <summary>
        /// Create a ResourcemanagerFolderIamPolicy resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ResourcemanagerFolderIamPolicy(string name, ResourcemanagerFolderIamPolicyArgs args, CustomResourceOptions? options = null)
            : base("yandex:index/resourcemanagerFolderIamPolicy:ResourcemanagerFolderIamPolicy", name, args ?? new ResourcemanagerFolderIamPolicyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ResourcemanagerFolderIamPolicy(string name, Input<string> id, ResourcemanagerFolderIamPolicyState? state = null, CustomResourceOptions? options = null)
            : base("yandex:index/resourcemanagerFolderIamPolicy:ResourcemanagerFolderIamPolicy", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ResourcemanagerFolderIamPolicy resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ResourcemanagerFolderIamPolicy Get(string name, Input<string> id, ResourcemanagerFolderIamPolicyState? state = null, CustomResourceOptions? options = null)
        {
            return new ResourcemanagerFolderIamPolicy(name, id, state, options);
        }
    }

    public sealed class ResourcemanagerFolderIamPolicyArgs : Pulumi.ResourceArgs
    {
        [Input("folderId", required: true)]
        public Input<string> FolderId { get; set; } = null!;

        [Input("policyData", required: true)]
        public Input<string> PolicyData { get; set; } = null!;

        public ResourcemanagerFolderIamPolicyArgs()
        {
        }
    }

    public sealed class ResourcemanagerFolderIamPolicyState : Pulumi.ResourceArgs
    {
        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        [Input("policyData")]
        public Input<string>? PolicyData { get; set; }

        public ResourcemanagerFolderIamPolicyState()
        {
        }
    }
}
