// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    [YandexResourceType("yandex:index/vpcSecurityGroup:VpcSecurityGroup")]
    public partial class VpcSecurityGroup : Pulumi.CustomResource
    {
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        [Output("egresses")]
        public Output<ImmutableArray<Outputs.VpcSecurityGroupEgress>> Egresses { get; private set; } = null!;

        [Output("folderId")]
        public Output<string> FolderId { get; private set; } = null!;

        [Output("ingresses")]
        public Output<ImmutableArray<Outputs.VpcSecurityGroupIngress>> Ingresses { get; private set; } = null!;

        [Output("labels")]
        public Output<ImmutableDictionary<string, string>?> Labels { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("networkId")]
        public Output<string> NetworkId { get; private set; } = null!;

        [Output("status")]
        public Output<string> Status { get; private set; } = null!;


        /// <summary>
        /// Create a VpcSecurityGroup resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public VpcSecurityGroup(string name, VpcSecurityGroupArgs args, CustomResourceOptions? options = null)
            : base("yandex:index/vpcSecurityGroup:VpcSecurityGroup", name, args ?? new VpcSecurityGroupArgs(), MakeResourceOptions(options, ""))
        {
        }

        private VpcSecurityGroup(string name, Input<string> id, VpcSecurityGroupState? state = null, CustomResourceOptions? options = null)
            : base("yandex:index/vpcSecurityGroup:VpcSecurityGroup", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing VpcSecurityGroup resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static VpcSecurityGroup Get(string name, Input<string> id, VpcSecurityGroupState? state = null, CustomResourceOptions? options = null)
        {
            return new VpcSecurityGroup(name, id, state, options);
        }
    }

    public sealed class VpcSecurityGroupArgs : Pulumi.ResourceArgs
    {
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("egresses")]
        private InputList<Inputs.VpcSecurityGroupEgressArgs>? _egresses;
        public InputList<Inputs.VpcSecurityGroupEgressArgs> Egresses
        {
            get => _egresses ?? (_egresses = new InputList<Inputs.VpcSecurityGroupEgressArgs>());
            set => _egresses = value;
        }

        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        [Input("ingresses")]
        private InputList<Inputs.VpcSecurityGroupIngressArgs>? _ingresses;
        public InputList<Inputs.VpcSecurityGroupIngressArgs> Ingresses
        {
            get => _ingresses ?? (_ingresses = new InputList<Inputs.VpcSecurityGroupIngressArgs>());
            set => _ingresses = value;
        }

        [Input("labels")]
        private InputMap<string>? _labels;
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("networkId", required: true)]
        public Input<string> NetworkId { get; set; } = null!;

        public VpcSecurityGroupArgs()
        {
        }
    }

    public sealed class VpcSecurityGroupState : Pulumi.ResourceArgs
    {
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("egresses")]
        private InputList<Inputs.VpcSecurityGroupEgressGetArgs>? _egresses;
        public InputList<Inputs.VpcSecurityGroupEgressGetArgs> Egresses
        {
            get => _egresses ?? (_egresses = new InputList<Inputs.VpcSecurityGroupEgressGetArgs>());
            set => _egresses = value;
        }

        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        [Input("ingresses")]
        private InputList<Inputs.VpcSecurityGroupIngressGetArgs>? _ingresses;
        public InputList<Inputs.VpcSecurityGroupIngressGetArgs> Ingresses
        {
            get => _ingresses ?? (_ingresses = new InputList<Inputs.VpcSecurityGroupIngressGetArgs>());
            set => _ingresses = value;
        }

        [Input("labels")]
        private InputMap<string>? _labels;
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("networkId")]
        public Input<string>? NetworkId { get; set; }

        [Input("status")]
        public Input<string>? Status { get; set; }

        public VpcSecurityGroupState()
        {
        }
    }
}
