// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type Function struct {
	pulumi.CustomResourceState

	Content          FunctionContentPtrOutput `pulumi:"content"`
	CreatedAt        pulumi.StringOutput      `pulumi:"createdAt"`
	Description      pulumi.StringPtrOutput   `pulumi:"description"`
	Entrypoint       pulumi.StringOutput      `pulumi:"entrypoint"`
	Environment      pulumi.StringMapOutput   `pulumi:"environment"`
	ExecutionTimeout pulumi.StringPtrOutput   `pulumi:"executionTimeout"`
	FolderId         pulumi.StringOutput      `pulumi:"folderId"`
	ImageSize        pulumi.IntOutput         `pulumi:"imageSize"`
	Labels           pulumi.StringMapOutput   `pulumi:"labels"`
	LoggroupId       pulumi.StringOutput      `pulumi:"loggroupId"`
	Memory           pulumi.IntOutput         `pulumi:"memory"`
	Name             pulumi.StringOutput      `pulumi:"name"`
	Package          FunctionPackagePtrOutput `pulumi:"package"`
	Runtime          pulumi.StringOutput      `pulumi:"runtime"`
	ServiceAccountId pulumi.StringPtrOutput   `pulumi:"serviceAccountId"`
	Tags             pulumi.StringArrayOutput `pulumi:"tags"`
	UserHash         pulumi.StringOutput      `pulumi:"userHash"`
	Version          pulumi.StringOutput      `pulumi:"version"`
}

// NewFunction registers a new resource with the given unique name, arguments, and options.
func NewFunction(ctx *pulumi.Context,
	name string, args *FunctionArgs, opts ...pulumi.ResourceOption) (*Function, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Entrypoint == nil {
		return nil, errors.New("invalid value for required argument 'Entrypoint'")
	}
	if args.Memory == nil {
		return nil, errors.New("invalid value for required argument 'Memory'")
	}
	if args.Runtime == nil {
		return nil, errors.New("invalid value for required argument 'Runtime'")
	}
	if args.UserHash == nil {
		return nil, errors.New("invalid value for required argument 'UserHash'")
	}
	var resource Function
	err := ctx.RegisterResource("yandex:index/function:Function", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFunction gets an existing Function resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFunction(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FunctionState, opts ...pulumi.ResourceOption) (*Function, error) {
	var resource Function
	err := ctx.ReadResource("yandex:index/function:Function", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Function resources.
type functionState struct {
	Content          *FunctionContent  `pulumi:"content"`
	CreatedAt        *string           `pulumi:"createdAt"`
	Description      *string           `pulumi:"description"`
	Entrypoint       *string           `pulumi:"entrypoint"`
	Environment      map[string]string `pulumi:"environment"`
	ExecutionTimeout *string           `pulumi:"executionTimeout"`
	FolderId         *string           `pulumi:"folderId"`
	ImageSize        *int              `pulumi:"imageSize"`
	Labels           map[string]string `pulumi:"labels"`
	LoggroupId       *string           `pulumi:"loggroupId"`
	Memory           *int              `pulumi:"memory"`
	Name             *string           `pulumi:"name"`
	Package          *FunctionPackage  `pulumi:"package"`
	Runtime          *string           `pulumi:"runtime"`
	ServiceAccountId *string           `pulumi:"serviceAccountId"`
	Tags             []string          `pulumi:"tags"`
	UserHash         *string           `pulumi:"userHash"`
	Version          *string           `pulumi:"version"`
}

type FunctionState struct {
	Content          FunctionContentPtrInput
	CreatedAt        pulumi.StringPtrInput
	Description      pulumi.StringPtrInput
	Entrypoint       pulumi.StringPtrInput
	Environment      pulumi.StringMapInput
	ExecutionTimeout pulumi.StringPtrInput
	FolderId         pulumi.StringPtrInput
	ImageSize        pulumi.IntPtrInput
	Labels           pulumi.StringMapInput
	LoggroupId       pulumi.StringPtrInput
	Memory           pulumi.IntPtrInput
	Name             pulumi.StringPtrInput
	Package          FunctionPackagePtrInput
	Runtime          pulumi.StringPtrInput
	ServiceAccountId pulumi.StringPtrInput
	Tags             pulumi.StringArrayInput
	UserHash         pulumi.StringPtrInput
	Version          pulumi.StringPtrInput
}

func (FunctionState) ElementType() reflect.Type {
	return reflect.TypeOf((*functionState)(nil)).Elem()
}

type functionArgs struct {
	Content          *FunctionContent  `pulumi:"content"`
	Description      *string           `pulumi:"description"`
	Entrypoint       string            `pulumi:"entrypoint"`
	Environment      map[string]string `pulumi:"environment"`
	ExecutionTimeout *string           `pulumi:"executionTimeout"`
	FolderId         *string           `pulumi:"folderId"`
	Labels           map[string]string `pulumi:"labels"`
	Memory           int               `pulumi:"memory"`
	Name             *string           `pulumi:"name"`
	Package          *FunctionPackage  `pulumi:"package"`
	Runtime          string            `pulumi:"runtime"`
	ServiceAccountId *string           `pulumi:"serviceAccountId"`
	Tags             []string          `pulumi:"tags"`
	UserHash         string            `pulumi:"userHash"`
}

// The set of arguments for constructing a Function resource.
type FunctionArgs struct {
	Content          FunctionContentPtrInput
	Description      pulumi.StringPtrInput
	Entrypoint       pulumi.StringInput
	Environment      pulumi.StringMapInput
	ExecutionTimeout pulumi.StringPtrInput
	FolderId         pulumi.StringPtrInput
	Labels           pulumi.StringMapInput
	Memory           pulumi.IntInput
	Name             pulumi.StringPtrInput
	Package          FunctionPackagePtrInput
	Runtime          pulumi.StringInput
	ServiceAccountId pulumi.StringPtrInput
	Tags             pulumi.StringArrayInput
	UserHash         pulumi.StringInput
}

func (FunctionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*functionArgs)(nil)).Elem()
}

type FunctionInput interface {
	pulumi.Input

	ToFunctionOutput() FunctionOutput
	ToFunctionOutputWithContext(ctx context.Context) FunctionOutput
}

func (*Function) ElementType() reflect.Type {
	return reflect.TypeOf((*Function)(nil))
}

func (i *Function) ToFunctionOutput() FunctionOutput {
	return i.ToFunctionOutputWithContext(context.Background())
}

func (i *Function) ToFunctionOutputWithContext(ctx context.Context) FunctionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FunctionOutput)
}

type FunctionOutput struct {
	*pulumi.OutputState
}

func (FunctionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Function)(nil))
}

func (o FunctionOutput) ToFunctionOutput() FunctionOutput {
	return o
}

func (o FunctionOutput) ToFunctionOutputWithContext(ctx context.Context) FunctionOutput {
	return o
}

func init() {
	pulumi.RegisterOutputType(FunctionOutput{})
}
