// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetClientconfig(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetClientconfigResult, error) {
	var rv GetClientconfigResult
	err := ctx.Invoke("yandex:index/getClientconfig:getClientconfig", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getClientconfig.
type GetClientconfigResult struct {
	CloudId  string `pulumi:"cloudId"`
	FolderId string `pulumi:"folderId"`
	IamToken string `pulumi:"iamToken"`
	// The provider-assigned unique ID for this managed resource.
	Id   string `pulumi:"id"`
	Zone string `pulumi:"zone"`
}
