// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupComputeSnapshot(ctx *pulumi.Context, args *LookupComputeSnapshotArgs, opts ...pulumi.InvokeOption) (*LookupComputeSnapshotResult, error) {
	var rv LookupComputeSnapshotResult
	err := ctx.Invoke("yandex:index/getComputeSnapshot:getComputeSnapshot", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getComputeSnapshot.
type LookupComputeSnapshotArgs struct {
	FolderId   *string `pulumi:"folderId"`
	Name       *string `pulumi:"name"`
	SnapshotId *string `pulumi:"snapshotId"`
}

// A collection of values returned by getComputeSnapshot.
type LookupComputeSnapshotResult struct {
	CreatedAt   string `pulumi:"createdAt"`
	Description string `pulumi:"description"`
	DiskSize    int    `pulumi:"diskSize"`
	FolderId    string `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id           string            `pulumi:"id"`
	Labels       map[string]string `pulumi:"labels"`
	Name         string            `pulumi:"name"`
	ProductIds   []string          `pulumi:"productIds"`
	SnapshotId   string            `pulumi:"snapshotId"`
	SourceDiskId string            `pulumi:"sourceDiskId"`
	Status       string            `pulumi:"status"`
	StorageSize  int               `pulumi:"storageSize"`
}
