// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupComputePlacementGroup(ctx *pulumi.Context, args *LookupComputePlacementGroupArgs, opts ...pulumi.InvokeOption) (*LookupComputePlacementGroupResult, error) {
	var rv LookupComputePlacementGroupResult
	err := ctx.Invoke("yandex:index/getComputePlacementGroup:getComputePlacementGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getComputePlacementGroup.
type LookupComputePlacementGroupArgs struct {
	Description *string           `pulumi:"description"`
	FolderId    *string           `pulumi:"folderId"`
	GroupId     *string           `pulumi:"groupId"`
	Labels      map[string]string `pulumi:"labels"`
	Name        *string           `pulumi:"name"`
}

// A collection of values returned by getComputePlacementGroup.
type LookupComputePlacementGroupResult struct {
	CreatedAt   string  `pulumi:"createdAt"`
	Description *string `pulumi:"description"`
	FolderId    string  `pulumi:"folderId"`
	GroupId     string  `pulumi:"groupId"`
	// The provider-assigned unique ID for this managed resource.
	Id     string            `pulumi:"id"`
	Labels map[string]string `pulumi:"labels"`
	Name   *string           `pulumi:"name"`
}
