// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupComputeInstance(ctx *pulumi.Context, args *LookupComputeInstanceArgs, opts ...pulumi.InvokeOption) (*LookupComputeInstanceResult, error) {
	var rv LookupComputeInstanceResult
	err := ctx.Invoke("yandex:index/getComputeInstance:getComputeInstance", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getComputeInstance.
type LookupComputeInstanceArgs struct {
	FolderId         *string                             `pulumi:"folderId"`
	InstanceId       *string                             `pulumi:"instanceId"`
	Name             *string                             `pulumi:"name"`
	PlacementPolicy  *GetComputeInstancePlacementPolicy  `pulumi:"placementPolicy"`
	SchedulingPolicy *GetComputeInstanceSchedulingPolicy `pulumi:"schedulingPolicy"`
}

// A collection of values returned by getComputeInstance.
type LookupComputeInstanceResult struct {
	BootDisk    GetComputeInstanceBootDisk `pulumi:"bootDisk"`
	CreatedAt   string                     `pulumi:"createdAt"`
	Description string                     `pulumi:"description"`
	FolderId    string                     `pulumi:"folderId"`
	Fqdn        string                     `pulumi:"fqdn"`
	// The provider-assigned unique ID for this managed resource.
	Id                      string                               `pulumi:"id"`
	InstanceId              string                               `pulumi:"instanceId"`
	Labels                  map[string]string                    `pulumi:"labels"`
	Metadata                map[string]string                    `pulumi:"metadata"`
	Name                    string                               `pulumi:"name"`
	NetworkAccelerationType string                               `pulumi:"networkAccelerationType"`
	NetworkInterfaces       []GetComputeInstanceNetworkInterface `pulumi:"networkInterfaces"`
	PlacementPolicy         *GetComputeInstancePlacementPolicy   `pulumi:"placementPolicy"`
	PlatformId              string                               `pulumi:"platformId"`
	Resources               GetComputeInstanceResources          `pulumi:"resources"`
	SchedulingPolicy        GetComputeInstanceSchedulingPolicy   `pulumi:"schedulingPolicy"`
	SecondaryDisks          []GetComputeInstanceSecondaryDisk    `pulumi:"secondaryDisks"`
	ServiceAccountId        string                               `pulumi:"serviceAccountId"`
	Status                  string                               `pulumi:"status"`
	Zone                    string                               `pulumi:"zone"`
}
