// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetIamUser(ctx *pulumi.Context, args *GetIamUserArgs, opts ...pulumi.InvokeOption) (*GetIamUserResult, error) {
	var rv GetIamUserResult
	err := ctx.Invoke("yandex:index/getIamUser:getIamUser", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIamUser.
type GetIamUserArgs struct {
	Login  *string `pulumi:"login"`
	UserId *string `pulumi:"userId"`
}

// A collection of values returned by getIamUser.
type GetIamUserResult struct {
	DefaultEmail string `pulumi:"defaultEmail"`
	// The provider-assigned unique ID for this managed resource.
	Id     string `pulumi:"id"`
	Login  string `pulumi:"login"`
	UserId string `pulumi:"userId"`
}
