// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupIotCoreDevice(ctx *pulumi.Context, args *LookupIotCoreDeviceArgs, opts ...pulumi.InvokeOption) (*LookupIotCoreDeviceResult, error) {
	var rv LookupIotCoreDeviceResult
	err := ctx.Invoke("yandex:index/getIotCoreDevice:getIotCoreDevice", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIotCoreDevice.
type LookupIotCoreDeviceArgs struct {
	DeviceId *string `pulumi:"deviceId"`
	Name     *string `pulumi:"name"`
}

// A collection of values returned by getIotCoreDevice.
type LookupIotCoreDeviceResult struct {
	Aliases      map[string]string `pulumi:"aliases"`
	Certificates []string          `pulumi:"certificates"`
	CreatedAt    string            `pulumi:"createdAt"`
	Description  string            `pulumi:"description"`
	DeviceId     *string           `pulumi:"deviceId"`
	// The provider-assigned unique ID for this managed resource.
	Id         string   `pulumi:"id"`
	Name       *string  `pulumi:"name"`
	Passwords  []string `pulumi:"passwords"`
	RegistryId string   `pulumi:"registryId"`
}
