// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupKubernetesCluster(ctx *pulumi.Context, args *LookupKubernetesClusterArgs, opts ...pulumi.InvokeOption) (*LookupKubernetesClusterResult, error) {
	var rv LookupKubernetesClusterResult
	err := ctx.Invoke("yandex:index/getKubernetesCluster:getKubernetesCluster", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getKubernetesCluster.
type LookupKubernetesClusterArgs struct {
	ClusterId *string `pulumi:"clusterId"`
	FolderId  *string `pulumi:"folderId"`
	Name      *string `pulumi:"name"`
}

// A collection of values returned by getKubernetesCluster.
type LookupKubernetesClusterResult struct {
	ClusterId        string `pulumi:"clusterId"`
	ClusterIpv4Range string `pulumi:"clusterIpv4Range"`
	CreatedAt        string `pulumi:"createdAt"`
	Description      string `pulumi:"description"`
	FolderId         string `pulumi:"folderId"`
	Health           string `pulumi:"health"`
	// The provider-assigned unique ID for this managed resource.
	Id                    string                          `pulumi:"id"`
	KmsProvider           GetKubernetesClusterKmsProvider `pulumi:"kmsProvider"`
	Labels                map[string]string               `pulumi:"labels"`
	Master                GetKubernetesClusterMaster      `pulumi:"master"`
	Name                  string                          `pulumi:"name"`
	NetworkId             string                          `pulumi:"networkId"`
	NetworkPolicyProvider string                          `pulumi:"networkPolicyProvider"`
	NodeIpv4CidrMaskSize  int                             `pulumi:"nodeIpv4CidrMaskSize"`
	NodeServiceAccountId  string                          `pulumi:"nodeServiceAccountId"`
	ReleaseChannel        string                          `pulumi:"releaseChannel"`
	ServiceAccountId      string                          `pulumi:"serviceAccountId"`
	ServiceIpv4Range      string                          `pulumi:"serviceIpv4Range"`
	Status                string                          `pulumi:"status"`
}
