// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupKubernetesNodeGroup(ctx *pulumi.Context, args *LookupKubernetesNodeGroupArgs, opts ...pulumi.InvokeOption) (*LookupKubernetesNodeGroupResult, error) {
	var rv LookupKubernetesNodeGroupResult
	err := ctx.Invoke("yandex:index/getKubernetesNodeGroup:getKubernetesNodeGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getKubernetesNodeGroup.
type LookupKubernetesNodeGroupArgs struct {
	FolderId    *string `pulumi:"folderId"`
	Name        *string `pulumi:"name"`
	NodeGroupId *string `pulumi:"nodeGroupId"`
}

// A collection of values returned by getKubernetesNodeGroup.
type LookupKubernetesNodeGroupResult struct {
	AllocationPolicy     GetKubernetesNodeGroupAllocationPolicy `pulumi:"allocationPolicy"`
	AllowedUnsafeSysctls []string                               `pulumi:"allowedUnsafeSysctls"`
	ClusterId            string                                 `pulumi:"clusterId"`
	CreatedAt            string                                 `pulumi:"createdAt"`
	DeployPolicy         GetKubernetesNodeGroupDeployPolicy     `pulumi:"deployPolicy"`
	Description          string                                 `pulumi:"description"`
	FolderId             string                                 `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id                string                                  `pulumi:"id"`
	InstanceGroupId   string                                  `pulumi:"instanceGroupId"`
	InstanceTemplate  GetKubernetesNodeGroupInstanceTemplate  `pulumi:"instanceTemplate"`
	Labels            map[string]string                       `pulumi:"labels"`
	MaintenancePolicy GetKubernetesNodeGroupMaintenancePolicy `pulumi:"maintenancePolicy"`
	Name              string                                  `pulumi:"name"`
	NodeGroupId       string                                  `pulumi:"nodeGroupId"`
	NodeLabels        map[string]string                       `pulumi:"nodeLabels"`
	NodeTaints        []string                                `pulumi:"nodeTaints"`
	ScalePolicy       GetKubernetesNodeGroupScalePolicy       `pulumi:"scalePolicy"`
	Status            string                                  `pulumi:"status"`
	VersionInfo       GetKubernetesNodeGroupVersionInfo       `pulumi:"versionInfo"`
}
