// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupMdbMongodbCluster(ctx *pulumi.Context, args *LookupMdbMongodbClusterArgs, opts ...pulumi.InvokeOption) (*LookupMdbMongodbClusterResult, error) {
	var rv LookupMdbMongodbClusterResult
	err := ctx.Invoke("yandex:index/getMdbMongodbCluster:getMdbMongodbCluster", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getMdbMongodbCluster.
type LookupMdbMongodbClusterArgs struct {
	ClusterId *string `pulumi:"clusterId"`
	FolderId  *string `pulumi:"folderId"`
	Name      *string `pulumi:"name"`
}

// A collection of values returned by getMdbMongodbCluster.
type LookupMdbMongodbClusterResult struct {
	ClusterConfig GetMdbMongodbClusterClusterConfig `pulumi:"clusterConfig"`
	ClusterId     string                            `pulumi:"clusterId"`
	CreatedAt     string                            `pulumi:"createdAt"`
	Databases     []GetMdbMongodbClusterDatabase    `pulumi:"databases"`
	Description   string                            `pulumi:"description"`
	Environment   string                            `pulumi:"environment"`
	FolderId      string                            `pulumi:"folderId"`
	Health        string                            `pulumi:"health"`
	Hosts         []GetMdbMongodbClusterHost        `pulumi:"hosts"`
	// The provider-assigned unique ID for this managed resource.
	Id               string                        `pulumi:"id"`
	Labels           map[string]string             `pulumi:"labels"`
	Name             string                        `pulumi:"name"`
	NetworkId        string                        `pulumi:"networkId"`
	Resources        GetMdbMongodbClusterResources `pulumi:"resources"`
	SecurityGroupIds []string                      `pulumi:"securityGroupIds"`
	Sharded          bool                          `pulumi:"sharded"`
	Status           string                        `pulumi:"status"`
	Users            []GetMdbMongodbClusterUser    `pulumi:"users"`
}
