// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupVpcNetwork(ctx *pulumi.Context, args *LookupVpcNetworkArgs, opts ...pulumi.InvokeOption) (*LookupVpcNetworkResult, error) {
	var rv LookupVpcNetworkResult
	err := ctx.Invoke("yandex:index/getVpcNetwork:getVpcNetwork", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVpcNetwork.
type LookupVpcNetworkArgs struct {
	FolderId  *string `pulumi:"folderId"`
	Name      *string `pulumi:"name"`
	NetworkId *string `pulumi:"networkId"`
}

// A collection of values returned by getVpcNetwork.
type LookupVpcNetworkResult struct {
	CreatedAt              string `pulumi:"createdAt"`
	DefaultSecurityGroupId string `pulumi:"defaultSecurityGroupId"`
	Description            string `pulumi:"description"`
	FolderId               string `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id        string            `pulumi:"id"`
	Labels    map[string]string `pulumi:"labels"`
	Name      string            `pulumi:"name"`
	NetworkId string            `pulumi:"networkId"`
	SubnetIds []string          `pulumi:"subnetIds"`
}
