// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupVpcRouteTable(ctx *pulumi.Context, args *LookupVpcRouteTableArgs, opts ...pulumi.InvokeOption) (*LookupVpcRouteTableResult, error) {
	var rv LookupVpcRouteTableResult
	err := ctx.Invoke("yandex:index/getVpcRouteTable:getVpcRouteTable", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVpcRouteTable.
type LookupVpcRouteTableArgs struct {
	FolderId     *string `pulumi:"folderId"`
	Name         *string `pulumi:"name"`
	RouteTableId *string `pulumi:"routeTableId"`
}

// A collection of values returned by getVpcRouteTable.
type LookupVpcRouteTableResult struct {
	CreatedAt   string `pulumi:"createdAt"`
	Description string `pulumi:"description"`
	FolderId    string `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id           string                        `pulumi:"id"`
	Labels       map[string]string             `pulumi:"labels"`
	Name         string                        `pulumi:"name"`
	NetworkId    string                        `pulumi:"networkId"`
	RouteTableId string                        `pulumi:"routeTableId"`
	StaticRoutes []GetVpcRouteTableStaticRoute `pulumi:"staticRoutes"`
}
