// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type IamServiceAccountIamPolicy struct {
	pulumi.CustomResourceState

	PolicyData       pulumi.StringOutput `pulumi:"policyData"`
	ServiceAccountId pulumi.StringOutput `pulumi:"serviceAccountId"`
}

// NewIamServiceAccountIamPolicy registers a new resource with the given unique name, arguments, and options.
func NewIamServiceAccountIamPolicy(ctx *pulumi.Context,
	name string, args *IamServiceAccountIamPolicyArgs, opts ...pulumi.ResourceOption) (*IamServiceAccountIamPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PolicyData == nil {
		return nil, errors.New("invalid value for required argument 'PolicyData'")
	}
	if args.ServiceAccountId == nil {
		return nil, errors.New("invalid value for required argument 'ServiceAccountId'")
	}
	var resource IamServiceAccountIamPolicy
	err := ctx.RegisterResource("yandex:index/iamServiceAccountIamPolicy:IamServiceAccountIamPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIamServiceAccountIamPolicy gets an existing IamServiceAccountIamPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIamServiceAccountIamPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IamServiceAccountIamPolicyState, opts ...pulumi.ResourceOption) (*IamServiceAccountIamPolicy, error) {
	var resource IamServiceAccountIamPolicy
	err := ctx.ReadResource("yandex:index/iamServiceAccountIamPolicy:IamServiceAccountIamPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IamServiceAccountIamPolicy resources.
type iamServiceAccountIamPolicyState struct {
	PolicyData       *string `pulumi:"policyData"`
	ServiceAccountId *string `pulumi:"serviceAccountId"`
}

type IamServiceAccountIamPolicyState struct {
	PolicyData       pulumi.StringPtrInput
	ServiceAccountId pulumi.StringPtrInput
}

func (IamServiceAccountIamPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*iamServiceAccountIamPolicyState)(nil)).Elem()
}

type iamServiceAccountIamPolicyArgs struct {
	PolicyData       string `pulumi:"policyData"`
	ServiceAccountId string `pulumi:"serviceAccountId"`
}

// The set of arguments for constructing a IamServiceAccountIamPolicy resource.
type IamServiceAccountIamPolicyArgs struct {
	PolicyData       pulumi.StringInput
	ServiceAccountId pulumi.StringInput
}

func (IamServiceAccountIamPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*iamServiceAccountIamPolicyArgs)(nil)).Elem()
}

type IamServiceAccountIamPolicyInput interface {
	pulumi.Input

	ToIamServiceAccountIamPolicyOutput() IamServiceAccountIamPolicyOutput
	ToIamServiceAccountIamPolicyOutputWithContext(ctx context.Context) IamServiceAccountIamPolicyOutput
}

func (*IamServiceAccountIamPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((*IamServiceAccountIamPolicy)(nil))
}

func (i *IamServiceAccountIamPolicy) ToIamServiceAccountIamPolicyOutput() IamServiceAccountIamPolicyOutput {
	return i.ToIamServiceAccountIamPolicyOutputWithContext(context.Background())
}

func (i *IamServiceAccountIamPolicy) ToIamServiceAccountIamPolicyOutputWithContext(ctx context.Context) IamServiceAccountIamPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IamServiceAccountIamPolicyOutput)
}

type IamServiceAccountIamPolicyOutput struct {
	*pulumi.OutputState
}

func (IamServiceAccountIamPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*IamServiceAccountIamPolicy)(nil))
}

func (o IamServiceAccountIamPolicyOutput) ToIamServiceAccountIamPolicyOutput() IamServiceAccountIamPolicyOutput {
	return o
}

func (o IamServiceAccountIamPolicyOutput) ToIamServiceAccountIamPolicyOutputWithContext(ctx context.Context) IamServiceAccountIamPolicyOutput {
	return o
}

func init() {
	pulumi.RegisterOutputType(IamServiceAccountIamPolicyOutput{})
}
