// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type VpcSubnetDhcpOptions struct {
	DomainName        *string  `pulumi:"domainName"`
	DomainNameServers []string `pulumi:"domainNameServers"`
	NtpServers        []string `pulumi:"ntpServers"`
}

// VpcSubnetDhcpOptionsInput is an input type that accepts VpcSubnetDhcpOptionsArgs and VpcSubnetDhcpOptionsOutput values.
// You can construct a concrete instance of `VpcSubnetDhcpOptionsInput` via:
//
//          VpcSubnetDhcpOptionsArgs{...}
type VpcSubnetDhcpOptionsInput interface {
	pulumi.Input

	ToVpcSubnetDhcpOptionsOutput() VpcSubnetDhcpOptionsOutput
	ToVpcSubnetDhcpOptionsOutputWithContext(context.Context) VpcSubnetDhcpOptionsOutput
}

type VpcSubnetDhcpOptionsArgs struct {
	DomainName        pulumi.StringPtrInput   `pulumi:"domainName"`
	DomainNameServers pulumi.StringArrayInput `pulumi:"domainNameServers"`
	NtpServers        pulumi.StringArrayInput `pulumi:"ntpServers"`
}

func (VpcSubnetDhcpOptionsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VpcSubnetDhcpOptions)(nil)).Elem()
}

func (i VpcSubnetDhcpOptionsArgs) ToVpcSubnetDhcpOptionsOutput() VpcSubnetDhcpOptionsOutput {
	return i.ToVpcSubnetDhcpOptionsOutputWithContext(context.Background())
}

func (i VpcSubnetDhcpOptionsArgs) ToVpcSubnetDhcpOptionsOutputWithContext(ctx context.Context) VpcSubnetDhcpOptionsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VpcSubnetDhcpOptionsOutput)
}

func (i VpcSubnetDhcpOptionsArgs) ToVpcSubnetDhcpOptionsPtrOutput() VpcSubnetDhcpOptionsPtrOutput {
	return i.ToVpcSubnetDhcpOptionsPtrOutputWithContext(context.Background())
}

func (i VpcSubnetDhcpOptionsArgs) ToVpcSubnetDhcpOptionsPtrOutputWithContext(ctx context.Context) VpcSubnetDhcpOptionsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VpcSubnetDhcpOptionsOutput).ToVpcSubnetDhcpOptionsPtrOutputWithContext(ctx)
}

// VpcSubnetDhcpOptionsPtrInput is an input type that accepts VpcSubnetDhcpOptionsArgs, VpcSubnetDhcpOptionsPtr and VpcSubnetDhcpOptionsPtrOutput values.
// You can construct a concrete instance of `VpcSubnetDhcpOptionsPtrInput` via:
//
//          VpcSubnetDhcpOptionsArgs{...}
//
//  or:
//
//          nil
type VpcSubnetDhcpOptionsPtrInput interface {
	pulumi.Input

	ToVpcSubnetDhcpOptionsPtrOutput() VpcSubnetDhcpOptionsPtrOutput
	ToVpcSubnetDhcpOptionsPtrOutputWithContext(context.Context) VpcSubnetDhcpOptionsPtrOutput
}

type vpcSubnetDhcpOptionsPtrType VpcSubnetDhcpOptionsArgs

func VpcSubnetDhcpOptionsPtr(v *VpcSubnetDhcpOptionsArgs) VpcSubnetDhcpOptionsPtrInput {
	return (*vpcSubnetDhcpOptionsPtrType)(v)
}

func (*vpcSubnetDhcpOptionsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**VpcSubnetDhcpOptions)(nil)).Elem()
}

func (i *vpcSubnetDhcpOptionsPtrType) ToVpcSubnetDhcpOptionsPtrOutput() VpcSubnetDhcpOptionsPtrOutput {
	return i.ToVpcSubnetDhcpOptionsPtrOutputWithContext(context.Background())
}

func (i *vpcSubnetDhcpOptionsPtrType) ToVpcSubnetDhcpOptionsPtrOutputWithContext(ctx context.Context) VpcSubnetDhcpOptionsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VpcSubnetDhcpOptionsPtrOutput)
}

type VpcSubnetDhcpOptionsOutput struct{ *pulumi.OutputState }

func (VpcSubnetDhcpOptionsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VpcSubnetDhcpOptions)(nil)).Elem()
}

func (o VpcSubnetDhcpOptionsOutput) ToVpcSubnetDhcpOptionsOutput() VpcSubnetDhcpOptionsOutput {
	return o
}

func (o VpcSubnetDhcpOptionsOutput) ToVpcSubnetDhcpOptionsOutputWithContext(ctx context.Context) VpcSubnetDhcpOptionsOutput {
	return o
}

func (o VpcSubnetDhcpOptionsOutput) ToVpcSubnetDhcpOptionsPtrOutput() VpcSubnetDhcpOptionsPtrOutput {
	return o.ToVpcSubnetDhcpOptionsPtrOutputWithContext(context.Background())
}

func (o VpcSubnetDhcpOptionsOutput) ToVpcSubnetDhcpOptionsPtrOutputWithContext(ctx context.Context) VpcSubnetDhcpOptionsPtrOutput {
	return o.ApplyT(func(v VpcSubnetDhcpOptions) *VpcSubnetDhcpOptions {
		return &v
	}).(VpcSubnetDhcpOptionsPtrOutput)
}
func (o VpcSubnetDhcpOptionsOutput) DomainName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VpcSubnetDhcpOptions) *string { return v.DomainName }).(pulumi.StringPtrOutput)
}

func (o VpcSubnetDhcpOptionsOutput) DomainNameServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v VpcSubnetDhcpOptions) []string { return v.DomainNameServers }).(pulumi.StringArrayOutput)
}

func (o VpcSubnetDhcpOptionsOutput) NtpServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v VpcSubnetDhcpOptions) []string { return v.NtpServers }).(pulumi.StringArrayOutput)
}

type VpcSubnetDhcpOptionsPtrOutput struct{ *pulumi.OutputState }

func (VpcSubnetDhcpOptionsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VpcSubnetDhcpOptions)(nil)).Elem()
}

func (o VpcSubnetDhcpOptionsPtrOutput) ToVpcSubnetDhcpOptionsPtrOutput() VpcSubnetDhcpOptionsPtrOutput {
	return o
}

func (o VpcSubnetDhcpOptionsPtrOutput) ToVpcSubnetDhcpOptionsPtrOutputWithContext(ctx context.Context) VpcSubnetDhcpOptionsPtrOutput {
	return o
}

func (o VpcSubnetDhcpOptionsPtrOutput) Elem() VpcSubnetDhcpOptionsOutput {
	return o.ApplyT(func(v *VpcSubnetDhcpOptions) VpcSubnetDhcpOptions { return *v }).(VpcSubnetDhcpOptionsOutput)
}

func (o VpcSubnetDhcpOptionsPtrOutput) DomainName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VpcSubnetDhcpOptions) *string {
		if v == nil {
			return nil
		}
		return v.DomainName
	}).(pulumi.StringPtrOutput)
}

func (o VpcSubnetDhcpOptionsPtrOutput) DomainNameServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *VpcSubnetDhcpOptions) []string {
		if v == nil {
			return nil
		}
		return v.DomainNameServers
	}).(pulumi.StringArrayOutput)
}

func (o VpcSubnetDhcpOptionsPtrOutput) NtpServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *VpcSubnetDhcpOptions) []string {
		if v == nil {
			return nil
		}
		return v.NtpServers
	}).(pulumi.StringArrayOutput)
}

type GetVpcSubnetDhcpOptions struct {
	DomainName        string   `pulumi:"domainName"`
	DomainNameServers []string `pulumi:"domainNameServers"`
	NtpServers        []string `pulumi:"ntpServers"`
}

// GetVpcSubnetDhcpOptionsInput is an input type that accepts GetVpcSubnetDhcpOptionsArgs and GetVpcSubnetDhcpOptionsOutput values.
// You can construct a concrete instance of `GetVpcSubnetDhcpOptionsInput` via:
//
//          GetVpcSubnetDhcpOptionsArgs{...}
type GetVpcSubnetDhcpOptionsInput interface {
	pulumi.Input

	ToGetVpcSubnetDhcpOptionsOutput() GetVpcSubnetDhcpOptionsOutput
	ToGetVpcSubnetDhcpOptionsOutputWithContext(context.Context) GetVpcSubnetDhcpOptionsOutput
}

type GetVpcSubnetDhcpOptionsArgs struct {
	DomainName        pulumi.StringInput      `pulumi:"domainName"`
	DomainNameServers pulumi.StringArrayInput `pulumi:"domainNameServers"`
	NtpServers        pulumi.StringArrayInput `pulumi:"ntpServers"`
}

func (GetVpcSubnetDhcpOptionsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpcSubnetDhcpOptions)(nil)).Elem()
}

func (i GetVpcSubnetDhcpOptionsArgs) ToGetVpcSubnetDhcpOptionsOutput() GetVpcSubnetDhcpOptionsOutput {
	return i.ToGetVpcSubnetDhcpOptionsOutputWithContext(context.Background())
}

func (i GetVpcSubnetDhcpOptionsArgs) ToGetVpcSubnetDhcpOptionsOutputWithContext(ctx context.Context) GetVpcSubnetDhcpOptionsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetVpcSubnetDhcpOptionsOutput)
}

type GetVpcSubnetDhcpOptionsOutput struct{ *pulumi.OutputState }

func (GetVpcSubnetDhcpOptionsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpcSubnetDhcpOptions)(nil)).Elem()
}

func (o GetVpcSubnetDhcpOptionsOutput) ToGetVpcSubnetDhcpOptionsOutput() GetVpcSubnetDhcpOptionsOutput {
	return o
}

func (o GetVpcSubnetDhcpOptionsOutput) ToGetVpcSubnetDhcpOptionsOutputWithContext(ctx context.Context) GetVpcSubnetDhcpOptionsOutput {
	return o
}

func (o GetVpcSubnetDhcpOptionsOutput) DomainName() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpcSubnetDhcpOptions) string { return v.DomainName }).(pulumi.StringOutput)
}

func (o GetVpcSubnetDhcpOptionsOutput) DomainNameServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetVpcSubnetDhcpOptions) []string { return v.DomainNameServers }).(pulumi.StringArrayOutput)
}

func (o GetVpcSubnetDhcpOptionsOutput) NtpServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetVpcSubnetDhcpOptions) []string { return v.NtpServers }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(VpcSubnetDhcpOptionsOutput{})
	pulumi.RegisterOutputType(VpcSubnetDhcpOptionsPtrOutput{})
	pulumi.RegisterOutputType(GetVpcSubnetDhcpOptionsOutput{})
}
