// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class ComputeInstanceGroupInstanceTemplateNetworkInterface
    {
        public readonly bool? Ipv4;
        public readonly bool? Ipv6;
        public readonly bool? Nat;
        public readonly string? NetworkId;
        public readonly ImmutableArray<string> SecurityGroupIds;
        public readonly ImmutableArray<string> SubnetIds;

        [OutputConstructor]
        private ComputeInstanceGroupInstanceTemplateNetworkInterface(
            bool? ipv4,

            bool? ipv6,

            bool? nat,

            string? networkId,

            ImmutableArray<string> securityGroupIds,

            ImmutableArray<string> subnetIds)
        {
            Ipv4 = ipv4;
            Ipv6 = ipv6;
            Nat = nat;
            NetworkId = networkId;
            SecurityGroupIds = securityGroupIds;
            SubnetIds = subnetIds;
        }
    }
}
