// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class ComputeInstanceGroupLoadBalancer
    {
        public readonly string? StatusMessage;
        public readonly string? TargetGroupDescription;
        public readonly string? TargetGroupId;
        public readonly ImmutableDictionary<string, string>? TargetGroupLabels;
        public readonly string? TargetGroupName;

        [OutputConstructor]
        private ComputeInstanceGroupLoadBalancer(
            string? statusMessage,

            string? targetGroupDescription,

            string? targetGroupId,

            ImmutableDictionary<string, string>? targetGroupLabels,

            string? targetGroupName)
        {
            StatusMessage = statusMessage;
            TargetGroupDescription = targetGroupDescription;
            TargetGroupId = targetGroupId;
            TargetGroupLabels = targetGroupLabels;
            TargetGroupName = targetGroupName;
        }
    }
}
