// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetComputeInstanceGroupInstanceNetworkInterfaceResult
    {
        public readonly int Index;
        public readonly string IpAddress;
        public readonly bool Ipv4;
        public readonly bool Ipv6;
        public readonly string Ipv6Address;
        public readonly string MacAddress;
        public readonly bool Nat;
        public readonly string NatIpAddress;
        public readonly string NatIpVersion;
        public readonly string SubnetId;

        [OutputConstructor]
        private GetComputeInstanceGroupInstanceNetworkInterfaceResult(
            int index,

            string ipAddress,

            bool ipv4,

            bool ipv6,

            string ipv6Address,

            string macAddress,

            bool nat,

            string natIpAddress,

            string natIpVersion,

            string subnetId)
        {
            Index = index;
            IpAddress = ipAddress;
            Ipv4 = ipv4;
            Ipv6 = ipv6;
            Ipv6Address = ipv6Address;
            MacAddress = macAddress;
            Nat = nat;
            NatIpAddress = natIpAddress;
            NatIpVersion = natIpVersion;
            SubnetId = subnetId;
        }
    }
}
