// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetComputeInstanceGroupInstanceTemplateBootDiskResult
    {
        public readonly string DeviceName;
        public readonly Outputs.GetComputeInstanceGroupInstanceTemplateBootDiskInitializeParamsResult InitializeParams;
        public readonly string Mode;

        [OutputConstructor]
        private GetComputeInstanceGroupInstanceTemplateBootDiskResult(
            string deviceName,

            Outputs.GetComputeInstanceGroupInstanceTemplateBootDiskInitializeParamsResult initializeParams,

            string mode)
        {
            DeviceName = deviceName;
            InitializeParams = initializeParams;
            Mode = mode;
        }
    }
}
