// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetDataprocClusterClusterConfigSubclusterSpecResult
    {
        public readonly int HostsCount;
        public readonly string Id;
        public readonly string Name;
        public readonly Outputs.GetDataprocClusterClusterConfigSubclusterSpecResourcesResult Resources;
        public readonly string Role;
        public readonly string SubnetId;

        [OutputConstructor]
        private GetDataprocClusterClusterConfigSubclusterSpecResult(
            int hostsCount,

            string id,

            string name,

            Outputs.GetDataprocClusterClusterConfigSubclusterSpecResourcesResult resources,

            string role,

            string subnetId)
        {
            HostsCount = hostsCount;
            Id = id;
            Name = name;
            Resources = resources;
            Role = role;
            SubnetId = subnetId;
        }
    }
}
