// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetLbNetworkLoadBalancerAttachedTargetGroupResult
    {
        public readonly ImmutableArray<Outputs.GetLbNetworkLoadBalancerAttachedTargetGroupHealthcheckResult> Healthchecks;
        public readonly string TargetGroupId;

        [OutputConstructor]
        private GetLbNetworkLoadBalancerAttachedTargetGroupResult(
            ImmutableArray<Outputs.GetLbNetworkLoadBalancerAttachedTargetGroupHealthcheckResult> healthchecks,

            string targetGroupId)
        {
            Healthchecks = healthchecks;
            TargetGroupId = targetGroupId;
        }
    }
}
