// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetMdbPostgresqlClusterConfigResult
    {
        public readonly Outputs.GetMdbPostgresqlClusterConfigAccessResult Access;
        public readonly bool Autofailover;
        public readonly Outputs.GetMdbPostgresqlClusterConfigBackupWindowStartResult BackupWindowStart;
        public readonly Outputs.GetMdbPostgresqlClusterConfigPerformanceDiagnosticsResult PerformanceDiagnostics;
        public readonly Outputs.GetMdbPostgresqlClusterConfigPoolerConfigResult PoolerConfig;
        public readonly ImmutableDictionary<string, string> PostgresqlConfig;
        public readonly Outputs.GetMdbPostgresqlClusterConfigResourcesResult Resources;
        public readonly string Version;

        [OutputConstructor]
        private GetMdbPostgresqlClusterConfigResult(
            Outputs.GetMdbPostgresqlClusterConfigAccessResult access,

            bool autofailover,

            Outputs.GetMdbPostgresqlClusterConfigBackupWindowStartResult backupWindowStart,

            Outputs.GetMdbPostgresqlClusterConfigPerformanceDiagnosticsResult performanceDiagnostics,

            Outputs.GetMdbPostgresqlClusterConfigPoolerConfigResult poolerConfig,

            ImmutableDictionary<string, string> postgresqlConfig,

            Outputs.GetMdbPostgresqlClusterConfigResourcesResult resources,

            string version)
        {
            Access = access;
            Autofailover = autofailover;
            BackupWindowStart = backupWindowStart;
            PerformanceDiagnostics = performanceDiagnostics;
            PoolerConfig = poolerConfig;
            PostgresqlConfig = postgresqlConfig;
            Resources = resources;
            Version = version;
        }
    }
}
