// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetMdbRedisClusterResourcesResult
    {
        public readonly int DiskSize;
        public readonly string ResourcePresetId;

        [OutputConstructor]
        private GetMdbRedisClusterResourcesResult(
            int diskSize,

            string resourcePresetId)
        {
            DiskSize = diskSize;
            ResourcePresetId = resourcePresetId;
        }
    }
}
