// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class KubernetesNodeGroupInstanceTemplate
    {
        public readonly Outputs.KubernetesNodeGroupInstanceTemplateBootDisk? BootDisk;
        public readonly ImmutableDictionary<string, string>? Metadata;
        public readonly bool? Nat;
        public readonly string? PlatformId;
        public readonly Outputs.KubernetesNodeGroupInstanceTemplateResources? Resources;
        public readonly Outputs.KubernetesNodeGroupInstanceTemplateSchedulingPolicy? SchedulingPolicy;

        [OutputConstructor]
        private KubernetesNodeGroupInstanceTemplate(
            Outputs.KubernetesNodeGroupInstanceTemplateBootDisk? bootDisk,

            ImmutableDictionary<string, string>? metadata,

            bool? nat,

            string? platformId,

            Outputs.KubernetesNodeGroupInstanceTemplateResources? resources,

            Outputs.KubernetesNodeGroupInstanceTemplateSchedulingPolicy? schedulingPolicy)
        {
            BootDisk = bootDisk;
            Metadata = metadata;
            Nat = nat;
            PlatformId = platformId;
            Resources = resources;
            SchedulingPolicy = schedulingPolicy;
        }
    }
}
