// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class LbNetworkLoad_balancerListener
    {
        public readonly Outputs.LbNetworkLoad_balancerListenerExternalAddressSpec? ExternalAddressSpec;
        public readonly Outputs.LbNetworkLoad_balancerListenerInternalAddressSpec? InternalAddressSpec;
        public readonly string Name;
        public readonly int Port;
        public readonly string? Protocol;
        public readonly int? TargetPort;

        [OutputConstructor]
        private LbNetworkLoad_balancerListener(
            Outputs.LbNetworkLoad_balancerListenerExternalAddressSpec? externalAddressSpec,

            Outputs.LbNetworkLoad_balancerListenerInternalAddressSpec? internalAddressSpec,

            string name,

            int port,

            string? protocol,

            int? targetPort)
        {
            ExternalAddressSpec = externalAddressSpec;
            InternalAddressSpec = internalAddressSpec;
            Name = name;
            Port = port;
            Protocol = protocol;
            TargetPort = targetPort;
        }
    }
}
