// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class MdbClickhouseClusterUser
    {
        public readonly string Name;
        public readonly string Password;
        public readonly ImmutableArray<Outputs.MdbClickhouseClusterUserPermission> Permissions;
        public readonly ImmutableArray<Outputs.MdbClickhouseClusterUserQuota> Quotas;
        public readonly Outputs.MdbClickhouseClusterUserSettings? Settings;

        [OutputConstructor]
        private MdbClickhouseClusterUser(
            string name,

            string password,

            ImmutableArray<Outputs.MdbClickhouseClusterUserPermission> permissions,

            ImmutableArray<Outputs.MdbClickhouseClusterUserQuota> quotas,

            Outputs.MdbClickhouseClusterUserSettings? settings)
        {
            Name = name;
            Password = password;
            Permissions = permissions;
            Quotas = quotas;
            Settings = settings;
        }
    }
}
