// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class MdbPostgresqlClusterHost
    {
        public readonly bool? AssignPublicIp;
        public readonly string? Fqdn;
        public readonly string? Name;
        public readonly int? Priority;
        public readonly string? ReplicationSource;
        public readonly string? ReplicationSourceName;
        public readonly string? Role;
        public readonly string? SubnetId;
        public readonly string Zone;

        [OutputConstructor]
        private MdbPostgresqlClusterHost(
            bool? assignPublicIp,

            string? fqdn,

            string? name,

            int? priority,

            string? replicationSource,

            string? replicationSourceName,

            string? role,

            string? subnetId,

            string zone)
        {
            AssignPublicIp = assignPublicIp;
            Fqdn = fqdn;
            Name = name;
            Priority = priority;
            ReplicationSource = replicationSource;
            ReplicationSourceName = replicationSourceName;
            Role = role;
            SubnetId = subnetId;
            Zone = zone;
        }
    }
}
