// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class StorageBucketLifecycleRule
    {
        public readonly int? AbortIncompleteMultipartUploadDays;
        public readonly bool Enabled;
        public readonly Outputs.StorageBucketLifecycleRuleExpiration? Expiration;
        public readonly string? Id;
        public readonly Outputs.StorageBucketLifecycleRuleNoncurrentVersionExpiration? NoncurrentVersionExpiration;
        public readonly ImmutableArray<Outputs.StorageBucketLifecycleRuleNoncurrentVersionTransition> NoncurrentVersionTransitions;
        public readonly string? Prefix;
        public readonly ImmutableArray<Outputs.StorageBucketLifecycleRuleTransition> Transitions;

        [OutputConstructor]
        private StorageBucketLifecycleRule(
            int? abortIncompleteMultipartUploadDays,

            bool enabled,

            Outputs.StorageBucketLifecycleRuleExpiration? expiration,

            string? id,

            Outputs.StorageBucketLifecycleRuleNoncurrentVersionExpiration? noncurrentVersionExpiration,

            ImmutableArray<Outputs.StorageBucketLifecycleRuleNoncurrentVersionTransition> noncurrentVersionTransitions,

            string? prefix,

            ImmutableArray<Outputs.StorageBucketLifecycleRuleTransition> transitions)
        {
            AbortIncompleteMultipartUploadDays = abortIncompleteMultipartUploadDays;
            Enabled = enabled;
            Expiration = expiration;
            Id = id;
            NoncurrentVersionExpiration = noncurrentVersionExpiration;
            NoncurrentVersionTransitions = noncurrentVersionTransitions;
            Prefix = prefix;
            Transitions = transitions;
        }
    }
}
