# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union
from . import _utilities, _tables

__all__ = [
    'GetClientconfigResult',
    'AwaitableGetClientconfigResult',
    'get_clientconfig',
]

@pulumi.output_type
class GetClientconfigResult:
    """
    A collection of values returned by getClientconfig.
    """
    def __init__(__self__, cloud_id=None, folder_id=None, iam_token=None, id=None, zone=None):
        if cloud_id and not isinstance(cloud_id, str):
            raise TypeError("Expected argument 'cloud_id' to be a str")
        pulumi.set(__self__, "cloud_id", cloud_id)
        if folder_id and not isinstance(folder_id, str):
            raise TypeError("Expected argument 'folder_id' to be a str")
        pulumi.set(__self__, "folder_id", folder_id)
        if iam_token and not isinstance(iam_token, str):
            raise TypeError("Expected argument 'iam_token' to be a str")
        pulumi.set(__self__, "iam_token", iam_token)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if zone and not isinstance(zone, str):
            raise TypeError("Expected argument 'zone' to be a str")
        pulumi.set(__self__, "zone", zone)

    @property
    @pulumi.getter(name="cloudId")
    def cloud_id(self) -> str:
        return pulumi.get(self, "cloud_id")

    @property
    @pulumi.getter(name="folderId")
    def folder_id(self) -> str:
        return pulumi.get(self, "folder_id")

    @property
    @pulumi.getter(name="iamToken")
    def iam_token(self) -> str:
        return pulumi.get(self, "iam_token")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def zone(self) -> str:
        return pulumi.get(self, "zone")


class AwaitableGetClientconfigResult(GetClientconfigResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetClientconfigResult(
            cloud_id=self.cloud_id,
            folder_id=self.folder_id,
            iam_token=self.iam_token,
            id=self.id,
            zone=self.zone)


def get_clientconfig(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetClientconfigResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    if opts is None:
        opts = pulumi.InvokeOptions()
    if opts.version is None:
        opts.version = _utilities.get_version()
    __ret__ = pulumi.runtime.invoke('yandex:index/getClientconfig:getClientconfig', __args__, opts=opts, typ=GetClientconfigResult).value

    return AwaitableGetClientconfigResult(
        cloud_id=__ret__.cloud_id,
        folder_id=__ret__.folder_id,
        iam_token=__ret__.iam_token,
        id=__ret__.id,
        zone=__ret__.zone)
