// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class ComputeInstanceGroupHealthCheckArgs : Pulumi.ResourceArgs
    {
        [Input("healthyThreshold")]
        public Input<int>? HealthyThreshold { get; set; }

        [Input("httpOptions")]
        private InputList<Inputs.ComputeInstanceGroupHealthCheckHttpOptionArgs>? _httpOptions;
        public InputList<Inputs.ComputeInstanceGroupHealthCheckHttpOptionArgs> HttpOptions
        {
            get => _httpOptions ?? (_httpOptions = new InputList<Inputs.ComputeInstanceGroupHealthCheckHttpOptionArgs>());
            set => _httpOptions = value;
        }

        [Input("interval")]
        public Input<int>? Interval { get; set; }

        [Input("tcpOptions")]
        private InputList<Inputs.ComputeInstanceGroupHealthCheckTcpOptionArgs>? _tcpOptions;
        public InputList<Inputs.ComputeInstanceGroupHealthCheckTcpOptionArgs> TcpOptions
        {
            get => _tcpOptions ?? (_tcpOptions = new InputList<Inputs.ComputeInstanceGroupHealthCheckTcpOptionArgs>());
            set => _tcpOptions = value;
        }

        [Input("timeout")]
        public Input<int>? Timeout { get; set; }

        [Input("unhealthyThreshold")]
        public Input<int>? UnhealthyThreshold { get; set; }

        public ComputeInstanceGroupHealthCheckArgs()
        {
        }
    }
}
