// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class KubernetesClusterMasterArgs : Pulumi.ResourceArgs
    {
        [Input("clusterCaCertificate")]
        public Input<string>? ClusterCaCertificate { get; set; }

        [Input("externalV4Address")]
        public Input<string>? ExternalV4Address { get; set; }

        [Input("externalV4Endpoint")]
        public Input<string>? ExternalV4Endpoint { get; set; }

        [Input("internalV4Address")]
        public Input<string>? InternalV4Address { get; set; }

        [Input("internalV4Endpoint")]
        public Input<string>? InternalV4Endpoint { get; set; }

        [Input("maintenancePolicy")]
        public Input<Inputs.KubernetesClusterMasterMaintenancePolicyArgs>? MaintenancePolicy { get; set; }

        [Input("publicIp")]
        public Input<bool>? PublicIp { get; set; }

        [Input("regional")]
        public Input<Inputs.KubernetesClusterMasterRegionalArgs>? Regional { get; set; }

        [Input("securityGroupIds")]
        private InputList<string>? _securityGroupIds;
        public InputList<string> SecurityGroupIds
        {
            get => _securityGroupIds ?? (_securityGroupIds = new InputList<string>());
            set => _securityGroupIds = value;
        }

        [Input("version")]
        public Input<string>? Version { get; set; }

        [Input("versionInfo")]
        public Input<Inputs.KubernetesClusterMasterVersionInfoArgs>? VersionInfo { get; set; }

        [Input("zonal")]
        public Input<Inputs.KubernetesClusterMasterZonalArgs>? Zonal { get; set; }

        public KubernetesClusterMasterArgs()
        {
        }
    }
}
