// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class MdbClickhouseClusterUserGetArgs : Pulumi.ResourceArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("password", required: true)]
        public Input<string> Password { get; set; } = null!;

        [Input("permissions")]
        private InputList<Inputs.MdbClickhouseClusterUserPermissionGetArgs>? _permissions;
        public InputList<Inputs.MdbClickhouseClusterUserPermissionGetArgs> Permissions
        {
            get => _permissions ?? (_permissions = new InputList<Inputs.MdbClickhouseClusterUserPermissionGetArgs>());
            set => _permissions = value;
        }

        [Input("quotas")]
        private InputList<Inputs.MdbClickhouseClusterUserQuotaGetArgs>? _quotas;
        public InputList<Inputs.MdbClickhouseClusterUserQuotaGetArgs> Quotas
        {
            get => _quotas ?? (_quotas = new InputList<Inputs.MdbClickhouseClusterUserQuotaGetArgs>());
            set => _quotas = value;
        }

        [Input("settings")]
        public Input<Inputs.MdbClickhouseClusterUserSettingsGetArgs>? Settings { get; set; }

        public MdbClickhouseClusterUserGetArgs()
        {
        }
    }
}
