// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class MdbClickhouseClusterUserQuotaArgs : Pulumi.ResourceArgs
    {
        [Input("errors")]
        public Input<int>? Errors { get; set; }

        [Input("executionTime")]
        public Input<int>? ExecutionTime { get; set; }

        [Input("intervalDuration", required: true)]
        public Input<int> IntervalDuration { get; set; } = null!;

        [Input("queries")]
        public Input<int>? Queries { get; set; }

        [Input("readRows")]
        public Input<int>? ReadRows { get; set; }

        [Input("resultRows")]
        public Input<int>? ResultRows { get; set; }

        public MdbClickhouseClusterUserQuotaArgs()
        {
        }
    }
}
