// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class MdbMongodbClusterHostGetArgs : Pulumi.ResourceArgs
    {
        [Input("assignPublicIp")]
        public Input<bool>? AssignPublicIp { get; set; }

        [Input("health")]
        public Input<string>? Health { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("role")]
        public Input<string>? Role { get; set; }

        [Input("shardName")]
        public Input<string>? ShardName { get; set; }

        [Input("subnetId", required: true)]
        public Input<string> SubnetId { get; set; } = null!;

        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("zoneId", required: true)]
        public Input<string> ZoneId { get; set; } = null!;

        public MdbMongodbClusterHostGetArgs()
        {
        }
    }
}
