// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class DataprocCluster extends pulumi.CustomResource {
    /**
     * Get an existing DataprocCluster resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DataprocClusterState, opts?: pulumi.CustomResourceOptions): DataprocCluster {
        return new DataprocCluster(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'yandex:index/dataprocCluster:DataprocCluster';

    /**
     * Returns true if the given object is an instance of DataprocCluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DataprocCluster {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DataprocCluster.__pulumiType;
    }

    public readonly bucket!: pulumi.Output<string | undefined>;
    public readonly clusterConfig!: pulumi.Output<outputs.DataprocClusterClusterConfig>;
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly folderId!: pulumi.Output<string>;
    public readonly labels!: pulumi.Output<{[key: string]: string} | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly serviceAccountId!: pulumi.Output<string>;
    public readonly uiProxy!: pulumi.Output<boolean | undefined>;
    public readonly zoneId!: pulumi.Output<string>;

    /**
     * Create a DataprocCluster resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DataprocClusterArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DataprocClusterArgs | DataprocClusterState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as DataprocClusterState | undefined;
            inputs["bucket"] = state ? state.bucket : undefined;
            inputs["clusterConfig"] = state ? state.clusterConfig : undefined;
            inputs["createdAt"] = state ? state.createdAt : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["folderId"] = state ? state.folderId : undefined;
            inputs["labels"] = state ? state.labels : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["serviceAccountId"] = state ? state.serviceAccountId : undefined;
            inputs["uiProxy"] = state ? state.uiProxy : undefined;
            inputs["zoneId"] = state ? state.zoneId : undefined;
        } else {
            const args = argsOrState as DataprocClusterArgs | undefined;
            if ((!args || args.clusterConfig === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'clusterConfig'");
            }
            if ((!args || args.serviceAccountId === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'serviceAccountId'");
            }
            inputs["bucket"] = args ? args.bucket : undefined;
            inputs["clusterConfig"] = args ? args.clusterConfig : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["folderId"] = args ? args.folderId : undefined;
            inputs["labels"] = args ? args.labels : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["serviceAccountId"] = args ? args.serviceAccountId : undefined;
            inputs["uiProxy"] = args ? args.uiProxy : undefined;
            inputs["zoneId"] = args ? args.zoneId : undefined;
            inputs["createdAt"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(DataprocCluster.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DataprocCluster resources.
 */
export interface DataprocClusterState {
    readonly bucket?: pulumi.Input<string>;
    readonly clusterConfig?: pulumi.Input<inputs.DataprocClusterClusterConfig>;
    readonly createdAt?: pulumi.Input<string>;
    readonly description?: pulumi.Input<string>;
    readonly folderId?: pulumi.Input<string>;
    readonly labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    readonly name?: pulumi.Input<string>;
    readonly serviceAccountId?: pulumi.Input<string>;
    readonly uiProxy?: pulumi.Input<boolean>;
    readonly zoneId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DataprocCluster resource.
 */
export interface DataprocClusterArgs {
    readonly bucket?: pulumi.Input<string>;
    readonly clusterConfig: pulumi.Input<inputs.DataprocClusterClusterConfig>;
    readonly description?: pulumi.Input<string>;
    readonly folderId?: pulumi.Input<string>;
    readonly labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    readonly name?: pulumi.Input<string>;
    readonly serviceAccountId: pulumi.Input<string>;
    readonly uiProxy?: pulumi.Input<boolean>;
    readonly zoneId?: pulumi.Input<string>;
}
