// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getClientconfig(opts?: pulumi.InvokeOptions): Promise<GetClientconfigResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("yandex:index/getClientconfig:getClientconfig", {
    }, opts);
}

/**
 * A collection of values returned by getClientconfig.
 */
export interface GetClientconfigResult {
    readonly cloudId: string;
    readonly folderId: string;
    readonly iamToken: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly zone: string;
}
