// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getComputeInstance(args?: GetComputeInstanceArgs, opts?: pulumi.InvokeOptions): Promise<GetComputeInstanceResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("yandex:index/getComputeInstance:getComputeInstance", {
        "folderId": args.folderId,
        "instanceId": args.instanceId,
        "name": args.name,
        "placementPolicy": args.placementPolicy,
        "schedulingPolicy": args.schedulingPolicy,
    }, opts);
}

/**
 * A collection of arguments for invoking getComputeInstance.
 */
export interface GetComputeInstanceArgs {
    readonly folderId?: string;
    readonly instanceId?: string;
    readonly name?: string;
    readonly placementPolicy?: inputs.GetComputeInstancePlacementPolicy;
    readonly schedulingPolicy?: inputs.GetComputeInstanceSchedulingPolicy;
}

/**
 * A collection of values returned by getComputeInstance.
 */
export interface GetComputeInstanceResult {
    readonly bootDisk: outputs.GetComputeInstanceBootDisk;
    readonly createdAt: string;
    readonly description: string;
    readonly folderId: string;
    readonly fqdn: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly instanceId: string;
    readonly labels: {[key: string]: string};
    readonly metadata: {[key: string]: string};
    readonly name: string;
    readonly networkAccelerationType: string;
    readonly networkInterfaces: outputs.GetComputeInstanceNetworkInterface[];
    readonly placementPolicy?: outputs.GetComputeInstancePlacementPolicy;
    readonly platformId: string;
    readonly resources: outputs.GetComputeInstanceResources;
    readonly schedulingPolicy: outputs.GetComputeInstanceSchedulingPolicy;
    readonly secondaryDisks: outputs.GetComputeInstanceSecondaryDisk[];
    readonly serviceAccountId: string;
    readonly status: string;
    readonly zone: string;
}
