// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getComputeSnapshot(args?: GetComputeSnapshotArgs, opts?: pulumi.InvokeOptions): Promise<GetComputeSnapshotResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("yandex:index/getComputeSnapshot:getComputeSnapshot", {
        "folderId": args.folderId,
        "name": args.name,
        "snapshotId": args.snapshotId,
    }, opts);
}

/**
 * A collection of arguments for invoking getComputeSnapshot.
 */
export interface GetComputeSnapshotArgs {
    readonly folderId?: string;
    readonly name?: string;
    readonly snapshotId?: string;
}

/**
 * A collection of values returned by getComputeSnapshot.
 */
export interface GetComputeSnapshotResult {
    readonly createdAt: string;
    readonly description: string;
    readonly diskSize: number;
    readonly folderId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly labels: {[key: string]: string};
    readonly name: string;
    readonly productIds: string[];
    readonly snapshotId: string;
    readonly sourceDiskId: string;
    readonly status: string;
    readonly storageSize: number;
}
