// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getFunction(args?: GetFunctionArgs, opts?: pulumi.InvokeOptions): Promise<GetFunctionResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("yandex:index/getFunction:getFunction", {
        "folderId": args.folderId,
        "functionId": args.functionId,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getFunction.
 */
export interface GetFunctionArgs {
    readonly folderId?: string;
    readonly functionId?: string;
    readonly name?: string;
}

/**
 * A collection of values returned by getFunction.
 */
export interface GetFunctionResult {
    readonly createdAt: string;
    readonly description: string;
    readonly entrypoint: string;
    readonly environment: {[key: string]: string};
    readonly executionTimeout: string;
    readonly folderId?: string;
    readonly functionId?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly imageSize: number;
    readonly labels: {[key: string]: string};
    readonly loggroupId: string;
    readonly memory: number;
    readonly name?: string;
    readonly runtime: string;
    readonly serviceAccountId: string;
    readonly tags: string[];
    readonly version: string;
}
