// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getMdbPostgresqlCluster(args?: GetMdbPostgresqlClusterArgs, opts?: pulumi.InvokeOptions): Promise<GetMdbPostgresqlClusterResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("yandex:index/getMdbPostgresqlCluster:getMdbPostgresqlCluster", {
        "clusterId": args.clusterId,
        "description": args.description,
        "folderId": args.folderId,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getMdbPostgresqlCluster.
 */
export interface GetMdbPostgresqlClusterArgs {
    readonly clusterId?: string;
    readonly description?: string;
    readonly folderId?: string;
    readonly name?: string;
}

/**
 * A collection of values returned by getMdbPostgresqlCluster.
 */
export interface GetMdbPostgresqlClusterResult {
    readonly clusterId: string;
    readonly config: outputs.GetMdbPostgresqlClusterConfig;
    readonly createdAt: string;
    readonly databases: outputs.GetMdbPostgresqlClusterDatabase[];
    readonly description?: string;
    readonly environment: string;
    readonly folderId: string;
    readonly health: string;
    readonly hosts: outputs.GetMdbPostgresqlClusterHost[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly labels: {[key: string]: string};
    readonly name: string;
    readonly networkId: string;
    readonly securityGroupIds: string[];
    readonly status: string;
    readonly users: outputs.GetMdbPostgresqlClusterUser[];
}
