// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class IamServiceAccountIamBinding extends pulumi.CustomResource {
    /**
     * Get an existing IamServiceAccountIamBinding resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IamServiceAccountIamBindingState, opts?: pulumi.CustomResourceOptions): IamServiceAccountIamBinding {
        return new IamServiceAccountIamBinding(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'yandex:index/iamServiceAccountIamBinding:IamServiceAccountIamBinding';

    /**
     * Returns true if the given object is an instance of IamServiceAccountIamBinding.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IamServiceAccountIamBinding {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IamServiceAccountIamBinding.__pulumiType;
    }

    public readonly members!: pulumi.Output<string[]>;
    public readonly role!: pulumi.Output<string>;
    public readonly serviceAccountId!: pulumi.Output<string>;
    public readonly sleepAfter!: pulumi.Output<number | undefined>;

    /**
     * Create a IamServiceAccountIamBinding resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IamServiceAccountIamBindingArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IamServiceAccountIamBindingArgs | IamServiceAccountIamBindingState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as IamServiceAccountIamBindingState | undefined;
            inputs["members"] = state ? state.members : undefined;
            inputs["role"] = state ? state.role : undefined;
            inputs["serviceAccountId"] = state ? state.serviceAccountId : undefined;
            inputs["sleepAfter"] = state ? state.sleepAfter : undefined;
        } else {
            const args = argsOrState as IamServiceAccountIamBindingArgs | undefined;
            if ((!args || args.members === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'members'");
            }
            if ((!args || args.role === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'role'");
            }
            if ((!args || args.serviceAccountId === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'serviceAccountId'");
            }
            inputs["members"] = args ? args.members : undefined;
            inputs["role"] = args ? args.role : undefined;
            inputs["serviceAccountId"] = args ? args.serviceAccountId : undefined;
            inputs["sleepAfter"] = args ? args.sleepAfter : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(IamServiceAccountIamBinding.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IamServiceAccountIamBinding resources.
 */
export interface IamServiceAccountIamBindingState {
    readonly members?: pulumi.Input<pulumi.Input<string>[]>;
    readonly role?: pulumi.Input<string>;
    readonly serviceAccountId?: pulumi.Input<string>;
    readonly sleepAfter?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a IamServiceAccountIamBinding resource.
 */
export interface IamServiceAccountIamBindingArgs {
    readonly members: pulumi.Input<pulumi.Input<string>[]>;
    readonly role: pulumi.Input<string>;
    readonly serviceAccountId: pulumi.Input<string>;
    readonly sleepAfter?: pulumi.Input<number>;
}
