// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class IotCoreDevice extends pulumi.CustomResource {
    /**
     * Get an existing IotCoreDevice resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IotCoreDeviceState, opts?: pulumi.CustomResourceOptions): IotCoreDevice {
        return new IotCoreDevice(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'yandex:index/iotCoreDevice:IotCoreDevice';

    /**
     * Returns true if the given object is an instance of IotCoreDevice.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IotCoreDevice {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IotCoreDevice.__pulumiType;
    }

    public readonly aliases!: pulumi.Output<{[key: string]: string} | undefined>;
    public readonly certificates!: pulumi.Output<string[] | undefined>;
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly passwords!: pulumi.Output<string[] | undefined>;
    public readonly registryId!: pulumi.Output<string>;

    /**
     * Create a IotCoreDevice resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IotCoreDeviceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IotCoreDeviceArgs | IotCoreDeviceState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as IotCoreDeviceState | undefined;
            inputs["aliases"] = state ? state.aliases : undefined;
            inputs["certificates"] = state ? state.certificates : undefined;
            inputs["createdAt"] = state ? state.createdAt : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["passwords"] = state ? state.passwords : undefined;
            inputs["registryId"] = state ? state.registryId : undefined;
        } else {
            const args = argsOrState as IotCoreDeviceArgs | undefined;
            if ((!args || args.registryId === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'registryId'");
            }
            inputs["aliases"] = args ? args.aliases : undefined;
            inputs["certificates"] = args ? args.certificates : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["passwords"] = args ? args.passwords : undefined;
            inputs["registryId"] = args ? args.registryId : undefined;
            inputs["createdAt"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(IotCoreDevice.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IotCoreDevice resources.
 */
export interface IotCoreDeviceState {
    readonly aliases?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    readonly certificates?: pulumi.Input<pulumi.Input<string>[]>;
    readonly createdAt?: pulumi.Input<string>;
    readonly description?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly passwords?: pulumi.Input<pulumi.Input<string>[]>;
    readonly registryId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IotCoreDevice resource.
 */
export interface IotCoreDeviceArgs {
    readonly aliases?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    readonly certificates?: pulumi.Input<pulumi.Input<string>[]>;
    readonly description?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly passwords?: pulumi.Input<pulumi.Input<string>[]>;
    readonly registryId: pulumi.Input<string>;
}
