// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class LbNetworkLoad_balancer extends pulumi.CustomResource {
    /**
     * Get an existing LbNetworkLoad_balancer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LbNetworkLoad_balancerState, opts?: pulumi.CustomResourceOptions): LbNetworkLoad_balancer {
        return new LbNetworkLoad_balancer(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'yandex:index/lbNetworkLoad_balancer:LbNetworkLoad_balancer';

    /**
     * Returns true if the given object is an instance of LbNetworkLoad_balancer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LbNetworkLoad_balancer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LbNetworkLoad_balancer.__pulumiType;
    }

    public readonly attachedTargetGroups!: pulumi.Output<outputs.LbNetworkLoad_balancerAttachedTargetGroup[] | undefined>;
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly folderId!: pulumi.Output<string>;
    public readonly labels!: pulumi.Output<{[key: string]: string} | undefined>;
    public readonly listeners!: pulumi.Output<outputs.LbNetworkLoad_balancerListener[] | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly regionId!: pulumi.Output<string | undefined>;
    public readonly type!: pulumi.Output<string | undefined>;

    /**
     * Create a LbNetworkLoad_balancer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: LbNetworkLoad_balancerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LbNetworkLoad_balancerArgs | LbNetworkLoad_balancerState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as LbNetworkLoad_balancerState | undefined;
            inputs["attachedTargetGroups"] = state ? state.attachedTargetGroups : undefined;
            inputs["createdAt"] = state ? state.createdAt : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["folderId"] = state ? state.folderId : undefined;
            inputs["labels"] = state ? state.labels : undefined;
            inputs["listeners"] = state ? state.listeners : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["regionId"] = state ? state.regionId : undefined;
            inputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as LbNetworkLoad_balancerArgs | undefined;
            inputs["attachedTargetGroups"] = args ? args.attachedTargetGroups : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["folderId"] = args ? args.folderId : undefined;
            inputs["labels"] = args ? args.labels : undefined;
            inputs["listeners"] = args ? args.listeners : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["regionId"] = args ? args.regionId : undefined;
            inputs["type"] = args ? args.type : undefined;
            inputs["createdAt"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(LbNetworkLoad_balancer.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LbNetworkLoad_balancer resources.
 */
export interface LbNetworkLoad_balancerState {
    readonly attachedTargetGroups?: pulumi.Input<pulumi.Input<inputs.LbNetworkLoad_balancerAttachedTargetGroup>[]>;
    readonly createdAt?: pulumi.Input<string>;
    readonly description?: pulumi.Input<string>;
    readonly folderId?: pulumi.Input<string>;
    readonly labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    readonly listeners?: pulumi.Input<pulumi.Input<inputs.LbNetworkLoad_balancerListener>[]>;
    readonly name?: pulumi.Input<string>;
    readonly regionId?: pulumi.Input<string>;
    readonly type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a LbNetworkLoad_balancer resource.
 */
export interface LbNetworkLoad_balancerArgs {
    readonly attachedTargetGroups?: pulumi.Input<pulumi.Input<inputs.LbNetworkLoad_balancerAttachedTargetGroup>[]>;
    readonly description?: pulumi.Input<string>;
    readonly folderId?: pulumi.Input<string>;
    readonly labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    readonly listeners?: pulumi.Input<pulumi.Input<inputs.LbNetworkLoad_balancerListener>[]>;
    readonly name?: pulumi.Input<string>;
    readonly regionId?: pulumi.Input<string>;
    readonly type?: pulumi.Input<string>;
}
