// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class MdbRedisCluster extends pulumi.CustomResource {
    /**
     * Get an existing MdbRedisCluster resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MdbRedisClusterState, opts?: pulumi.CustomResourceOptions): MdbRedisCluster {
        return new MdbRedisCluster(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'yandex:index/mdbRedisCluster:MdbRedisCluster';

    /**
     * Returns true if the given object is an instance of MdbRedisCluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MdbRedisCluster {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MdbRedisCluster.__pulumiType;
    }

    public readonly config!: pulumi.Output<outputs.MdbRedisClusterConfig>;
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly environment!: pulumi.Output<string>;
    public readonly folderId!: pulumi.Output<string>;
    public /*out*/ readonly health!: pulumi.Output<string>;
    public readonly hosts!: pulumi.Output<outputs.MdbRedisClusterHost[]>;
    public readonly labels!: pulumi.Output<{[key: string]: string} | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly networkId!: pulumi.Output<string>;
    public readonly resources!: pulumi.Output<outputs.MdbRedisClusterResources>;
    public readonly securityGroupIds!: pulumi.Output<string[] | undefined>;
    public readonly sharded!: pulumi.Output<boolean | undefined>;
    public /*out*/ readonly status!: pulumi.Output<string>;

    /**
     * Create a MdbRedisCluster resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MdbRedisClusterArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MdbRedisClusterArgs | MdbRedisClusterState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as MdbRedisClusterState | undefined;
            inputs["config"] = state ? state.config : undefined;
            inputs["createdAt"] = state ? state.createdAt : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["environment"] = state ? state.environment : undefined;
            inputs["folderId"] = state ? state.folderId : undefined;
            inputs["health"] = state ? state.health : undefined;
            inputs["hosts"] = state ? state.hosts : undefined;
            inputs["labels"] = state ? state.labels : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["networkId"] = state ? state.networkId : undefined;
            inputs["resources"] = state ? state.resources : undefined;
            inputs["securityGroupIds"] = state ? state.securityGroupIds : undefined;
            inputs["sharded"] = state ? state.sharded : undefined;
            inputs["status"] = state ? state.status : undefined;
        } else {
            const args = argsOrState as MdbRedisClusterArgs | undefined;
            if ((!args || args.config === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'config'");
            }
            if ((!args || args.environment === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'environment'");
            }
            if ((!args || args.hosts === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'hosts'");
            }
            if ((!args || args.networkId === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'networkId'");
            }
            if ((!args || args.resources === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'resources'");
            }
            inputs["config"] = args ? args.config : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["environment"] = args ? args.environment : undefined;
            inputs["folderId"] = args ? args.folderId : undefined;
            inputs["hosts"] = args ? args.hosts : undefined;
            inputs["labels"] = args ? args.labels : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["networkId"] = args ? args.networkId : undefined;
            inputs["resources"] = args ? args.resources : undefined;
            inputs["securityGroupIds"] = args ? args.securityGroupIds : undefined;
            inputs["sharded"] = args ? args.sharded : undefined;
            inputs["createdAt"] = undefined /*out*/;
            inputs["health"] = undefined /*out*/;
            inputs["status"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(MdbRedisCluster.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering MdbRedisCluster resources.
 */
export interface MdbRedisClusterState {
    readonly config?: pulumi.Input<inputs.MdbRedisClusterConfig>;
    readonly createdAt?: pulumi.Input<string>;
    readonly description?: pulumi.Input<string>;
    readonly environment?: pulumi.Input<string>;
    readonly folderId?: pulumi.Input<string>;
    readonly health?: pulumi.Input<string>;
    readonly hosts?: pulumi.Input<pulumi.Input<inputs.MdbRedisClusterHost>[]>;
    readonly labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    readonly name?: pulumi.Input<string>;
    readonly networkId?: pulumi.Input<string>;
    readonly resources?: pulumi.Input<inputs.MdbRedisClusterResources>;
    readonly securityGroupIds?: pulumi.Input<pulumi.Input<string>[]>;
    readonly sharded?: pulumi.Input<boolean>;
    readonly status?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a MdbRedisCluster resource.
 */
export interface MdbRedisClusterArgs {
    readonly config: pulumi.Input<inputs.MdbRedisClusterConfig>;
    readonly description?: pulumi.Input<string>;
    readonly environment: pulumi.Input<string>;
    readonly folderId?: pulumi.Input<string>;
    readonly hosts: pulumi.Input<pulumi.Input<inputs.MdbRedisClusterHost>[]>;
    readonly labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    readonly name?: pulumi.Input<string>;
    readonly networkId: pulumi.Input<string>;
    readonly resources: pulumi.Input<inputs.MdbRedisClusterResources>;
    readonly securityGroupIds?: pulumi.Input<pulumi.Input<string>[]>;
    readonly sharded?: pulumi.Input<boolean>;
}
