// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class MessageQueue extends pulumi.CustomResource {
    /**
     * Get an existing MessageQueue resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MessageQueueState, opts?: pulumi.CustomResourceOptions): MessageQueue {
        return new MessageQueue(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'yandex:index/messageQueue:MessageQueue';

    /**
     * Returns true if the given object is an instance of MessageQueue.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MessageQueue {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MessageQueue.__pulumiType;
    }

    public readonly accessKey!: pulumi.Output<string | undefined>;
    public /*out*/ readonly arn!: pulumi.Output<string>;
    public readonly contentBasedDeduplication!: pulumi.Output<boolean | undefined>;
    public readonly delaySeconds!: pulumi.Output<number | undefined>;
    public readonly fifoQueue!: pulumi.Output<boolean | undefined>;
    public readonly maxMessageSize!: pulumi.Output<number | undefined>;
    public readonly messageRetentionSeconds!: pulumi.Output<number | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly namePrefix!: pulumi.Output<string | undefined>;
    public readonly receiveWaitTimeSeconds!: pulumi.Output<number | undefined>;
    public readonly redrivePolicy!: pulumi.Output<string | undefined>;
    public readonly secretKey!: pulumi.Output<string | undefined>;
    public readonly visibilityTimeoutSeconds!: pulumi.Output<number | undefined>;

    /**
     * Create a MessageQueue resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: MessageQueueArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MessageQueueArgs | MessageQueueState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as MessageQueueState | undefined;
            inputs["accessKey"] = state ? state.accessKey : undefined;
            inputs["arn"] = state ? state.arn : undefined;
            inputs["contentBasedDeduplication"] = state ? state.contentBasedDeduplication : undefined;
            inputs["delaySeconds"] = state ? state.delaySeconds : undefined;
            inputs["fifoQueue"] = state ? state.fifoQueue : undefined;
            inputs["maxMessageSize"] = state ? state.maxMessageSize : undefined;
            inputs["messageRetentionSeconds"] = state ? state.messageRetentionSeconds : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["namePrefix"] = state ? state.namePrefix : undefined;
            inputs["receiveWaitTimeSeconds"] = state ? state.receiveWaitTimeSeconds : undefined;
            inputs["redrivePolicy"] = state ? state.redrivePolicy : undefined;
            inputs["secretKey"] = state ? state.secretKey : undefined;
            inputs["visibilityTimeoutSeconds"] = state ? state.visibilityTimeoutSeconds : undefined;
        } else {
            const args = argsOrState as MessageQueueArgs | undefined;
            inputs["accessKey"] = args ? args.accessKey : undefined;
            inputs["contentBasedDeduplication"] = args ? args.contentBasedDeduplication : undefined;
            inputs["delaySeconds"] = args ? args.delaySeconds : undefined;
            inputs["fifoQueue"] = args ? args.fifoQueue : undefined;
            inputs["maxMessageSize"] = args ? args.maxMessageSize : undefined;
            inputs["messageRetentionSeconds"] = args ? args.messageRetentionSeconds : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["namePrefix"] = args ? args.namePrefix : undefined;
            inputs["receiveWaitTimeSeconds"] = args ? args.receiveWaitTimeSeconds : undefined;
            inputs["redrivePolicy"] = args ? args.redrivePolicy : undefined;
            inputs["secretKey"] = args ? args.secretKey : undefined;
            inputs["visibilityTimeoutSeconds"] = args ? args.visibilityTimeoutSeconds : undefined;
            inputs["arn"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(MessageQueue.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering MessageQueue resources.
 */
export interface MessageQueueState {
    readonly accessKey?: pulumi.Input<string>;
    readonly arn?: pulumi.Input<string>;
    readonly contentBasedDeduplication?: pulumi.Input<boolean>;
    readonly delaySeconds?: pulumi.Input<number>;
    readonly fifoQueue?: pulumi.Input<boolean>;
    readonly maxMessageSize?: pulumi.Input<number>;
    readonly messageRetentionSeconds?: pulumi.Input<number>;
    readonly name?: pulumi.Input<string>;
    readonly namePrefix?: pulumi.Input<string>;
    readonly receiveWaitTimeSeconds?: pulumi.Input<number>;
    readonly redrivePolicy?: pulumi.Input<string>;
    readonly secretKey?: pulumi.Input<string>;
    readonly visibilityTimeoutSeconds?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a MessageQueue resource.
 */
export interface MessageQueueArgs {
    readonly accessKey?: pulumi.Input<string>;
    readonly contentBasedDeduplication?: pulumi.Input<boolean>;
    readonly delaySeconds?: pulumi.Input<number>;
    readonly fifoQueue?: pulumi.Input<boolean>;
    readonly maxMessageSize?: pulumi.Input<number>;
    readonly messageRetentionSeconds?: pulumi.Input<number>;
    readonly name?: pulumi.Input<string>;
    readonly namePrefix?: pulumi.Input<string>;
    readonly receiveWaitTimeSeconds?: pulumi.Input<number>;
    readonly redrivePolicy?: pulumi.Input<string>;
    readonly secretKey?: pulumi.Input<string>;
    readonly visibilityTimeoutSeconds?: pulumi.Input<number>;
}
